"""
Django settings for literev legal project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from __future__ import annotations

import logging
import multiprocessing as mp
import os

from pathlib import Path
from typing import Any, Optional

import environ

# Ensure that logging captures warnings issued by warnings.warn()
logging.captureWarnings(True)

ROOT_DIR = Path(__file__).resolve().parent.parent.parent.parent

# Ensure that warnings are enabled
os.environ["PYTHONWARNINGS"] = "default"

env = environ.Env()

SERVICE_NAME = "literev"

# HTTP redirect is issued to the same URL
APPEND_SLASH = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

DOCKER_VOLUME_CONTAINER_PATH = Path(
    env("DOCKER_VOLUME_CONTAINER_PATH", default="/tmp/literev/files")
)

# TEMP_DATA = ROOT_DIR / "tmp"

# define the repertory where there is aul temporary data
TEMPORARY_DATA = DOCKER_VOLUME_CONTAINER_PATH / "data"
ARTICLE_DATA = DOCKER_VOLUME_CONTAINER_PATH / "articles"
PLOT_DATA = DOCKER_VOLUME_CONTAINER_PATH / "plot"

for dir in [TEMPORARY_DATA, ARTICLE_DATA, PLOT_DATA]:
    os.makedirs(dir, exist_ok=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# === env variables ===

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

DEBUG = env.bool("DEBUG", default=False)

# Get OpenAI API key
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

APP_NAME = "literev"
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "literev",
    *env("ALLOWED_HOSTS", default="").split(","),
]

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

THIRD_PARTY_APPS = [
    # "oauth2_provider",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.orcid",
    # "rest_framework",
]

LOCAL_CONFIG_APP = ["literev.apps.LiterevConfig"]

LOCAL_APPS = [
    "literev",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(PLOT_DATA) + "/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": True,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.settings_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES: dict[str, dict[str, Any]] = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("POSTGRES_DB_LITEREV", "x_db_name_x"),
        "USER": os.environ.get("POSTGRES_USER_LITEREV", "x_db_user_name_x"),
        "PASSWORD": os.environ.get(
            "POSTGRES_PASSWORD_LITEREV", "x_db_password_x"
        ),
        "HOST": os.environ.get("POSTGRES_HOST", "x_db_host_x"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        # 'OPTIONS': {'sslmode': 'require'}
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
_validation_module = "django.contrib.auth.password_validation"
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": f"{_validation_module}.UserAttributeSimilarityValidator"},
    {"NAME": f"{_validation_module}.MinimumLengthValidator"},
    {"NAME": f"{_validation_module}.CommonPasswordValidator"},
    {"NAME": f"{_validation_module}.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CELERY SETTINGS
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER", default="")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BROKER", default="")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"
CELERY_ACCEPT_CONTENT = ["pickle"]

# AUTH_USER_MODEL = "literev.CustomUser"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
    ("css", os.path.join(BASE_DIR, "static/css")),
    ("js", os.path.join(BASE_DIR, "static/js")),
    ("images", os.path.join(BASE_DIR, "static/images")),
    ("webfonts", os.path.join(BASE_DIR, "static/webfonts")),
]
STATIC_ROOT = os.environ.get("STATIC_ROOT") or str(BASE_DIR / "staticfiles")

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

MEDIA_ROOT = env("DJANGO_MEDIA_ROOT", default="/tmp/literev/media")

MEDIA_URL = "/media/"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000

NUMBER_THREADS_ALLOWED = env.int(
    "NUMBER_THREADS_ALLOWED", default=mp.cpu_count()
)
NUMBER_TRIALS = env.int("NUMBER_TRIALS", default=10)
NUMBER_ARTICLE_BY_PAGE = env.int("NUMBER_ARTICLE_BY_PAGE", default=30)

# SECURITY

# https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-httponly
SESSION_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/dev/ref/settings/#csrf-cookie-httponly
CSRF_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-browser-xss-filter
SECURE_BROWSER_XSS_FILTER = True
# https://docs.djangoproject.com/en/dev/ref/settings/#x-frame-options
X_FRAME_OPTIONS = "DENY"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
]

# django-allauth
# ----------------------------------------------------------------------------
# https://django-allauth.readthedocs.io/en/latest/configuration.html

ACCOUNT_ALLOW_REGISTRATION = env.bool(
    "DJANGO_ACCOUNT_ALLOW_REGISTRATION", True
)
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# ACCOUNT_LOGOUT_ON_GET = True

ACCOUNT_USER_MODEL_USERNAME_FIELD: Optional[str] = None
ACCOUNT_USERNAME_REQUIRED = False

# WORKAROUND TO USE THE CUSTOM LOGINFORM
# ACCOUNT_FORMS = {'login': 'literev.forms.LoginForm'}

# To sent emails from the webapp in the terminal
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

SITE_ID = 1

LOGIN_REDIRECT_URL = "/search/"
LOGOUT_REDIRECT_URL = "/"

DOWNLOAD_PDF_ARTICLE = False

# CACHE CONFIGURATION
CACHE_DIR = Path(env("LITEREV_CACHE_DIR", default="/tmp/literev/cache"))
CACHE_ACTIVE = env.bool("LITEREV_CACHE_ACTIVE", False)
CACHE_EXPIRATION = 3600  # seconds

# LOGGING

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Log research summary
# see more in workflow.libs.summary_log.py
LOG_RESEARCH_SUMMARY = env.bool("LOG_RESEARCH_SUMMARY", default=False)

# Deactivate all collectors
DEACTIVATE_ALL_COLLECTORS = env.bool(
    "DEACTIVATE_ALL_COLLECTORS", default=False
)

# ELASTICSEARCH
ES_HOST_URL = os.environ.get("ES_HOST_URL")
ES_USERNAME = os.environ.get("ES_USERNAME")
ES_PASSWORD = os.environ.get("ES_PASSWORD")

# TODO: Solve this duplicated name
# ELASTICSEARCH
ES_HOST_URL = os.environ.get(
    "ES_HOST_URL", default=""
)  # e.g.: "http://localhost:9200"
ES_USERNAME = os.environ.get(
    "ES_USERNAME", default=""
)  # Elastic Search username
ES_PASSWORD = os.environ.get(
    "ES_PASSWORD", default=""
)  # Elastic Search password
