"""
Django settings for literev legal project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import logging

from config.settings.base import *  # noqa: F403

SECURE_SSL_REDIRECT = False

INSTALLED_APPS += [  # NOQA F405
    # https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config
    "debug_toolbar",
    # https://django-extensions.readthedocs.io/en/latest/installation_instructions.html#configuration
    "django_extensions",
]

MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]  # noqa: F405

# DEBUG TOOLBAR
# ----------------------------------------------------------------------------
DEBUG_TOOLBAR_CONFIG = {
    "DISABLE_PANELS": ["debug_toolbar.panels.redirects.RedirectsPanel"],
    "SHOW_TEMPLATE_CONTEXT": True,
}
# https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#internal-ips
INTERNAL_IPS = ["127.0.0.1", "10.0.2.2"]

# need to explitly define the domains that send
# csrf_tokens otherwise all post requests will fail
CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "https://127.0.0.1",
]

LOGGING_LEVEL = logging.INFO
