# Generated by Django 5.0.4 on 2024-04-19 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0002_document_prepared_for_ngrams'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_display', models.BooleanField(default=True)),
                ('is_initial', models.BooleanField(default=True)),
                ('is_check', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.project')),
            ],
        ),
    ]
