# Generated by Django 5.1.2 on 2024-10-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0010_project_selected_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='standards',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
