# Generated by Django 5.2.9 on 2026-02-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0024_project_elastic_search_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='elastic_search_query',
        ),
    ]
