ENV=${ENV}
DEBUG=${DEBUG}
HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}

POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB_LITEREV=${POSTGRES_DB_LITEREV}
POSTGRES_USER_LITEREV=${POSTGRES_USER_LITEREV}
POSTGRES_PASSWORD_LITEREV=${POSTGRES_PASSWORD_LITEREV}
POSTGRES_DATA=${POSTGRES_DATA}
POSTGRES_HOST_BACKUP=${POSTGRES_HOST_BACKUP}

FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}

CONTAINER_VOLUME_DATA_DIR=${CONTAINER_VOLUME_DATA_DIR}
STATIC_ROOT=${STATIC_ROOT}
LITEREV_CACHE_DIR=${LITEREV_CACHE_DIR}

OPENAI_API_KEY=${OPENAI_API_KEY}
HACTAR_API_KEY=${HACTAR_API_KEY}
USE_HACTAR_LLM=${USE_HACTAR_LLM}
HACTAR_VERIFY_SSL=${HACTAR_VERIFY_SSL}

ALLOWED_HOSTS=${ALLOWED_HOSTS}
DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

MEDIA_ROOT=${MEDIA_ROOT}
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}

USE_CONTAINER=${USE_CONTAINER}
DOCKER_CPU_LIMIT=${DOCKER_CPU_LIMIT}
DOCKER_CPU_RESERVATION=${DOCKER_CPU_RESERVATION}

GUNICORN_WORKERS=${GUNICORN_WORKERS}

CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
CERTBOT_CONF=${CERTBOT_CONF}
CERTBOT_WWW=${CERTBOT_WWW}

ES_PORT=${ES_PORT}
ES_HOST_URL=${ES_HOST_URL}
ES_HOSTNAME=${ES_HOSTNAME}
ES_USERNAME=${ES_USERNAME}
ES_PASSWORD=${ES_PASSWORD}
ES_CERTIF=${ES_CERTIF}
ES_STACK_VERSION=${ES_STACK_VERSION}

NGNIX_CONF=${NGNIX_CONF}

CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY}
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_DB=${REDIS_DB}

NUMBER_ARTICLE_BY_PAGE=${NUMBER_ARTICLE_BY_PAGE}
NUMBER_THREADS_ALLOWED=${NUMBER_THREADS_ALLOWED}
NUMBER_TRIALS=${NUMBER_TRIALS}
NUMBER_OPTUNA_JOBS=${NUMBER_OPTUNA_JOBS}
UPDATE_INTERVAL=${UPDATE_INTERVAL}

PROCESS-ALL-CORPUS-LITEREV=${PROCESS-ALL-CORPUS-LITEREV}

CLUSTERING_MIN_DOCUMENTS=${CLUSTERING_MIN_DOCUMENTS}
SENTRY_DSN=${SENTRY_DSN}

MIN_CONFIDENCE=${MIN_CONFIDENCE}
LITEREV_NOTEBOOKS_DIR=${LITEREV_NOTEBOOKS_DIR}
