ENV=${ENV}
DEBUG=${DEBUG}

POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB_LITEREV=${POSTGRES_DB_LITEREV}
POSTGRES_USER_LITEREV=${POSTGRES_USER_LITEREV}
POSTGRES_PASSWORD_LITEREV=${POSTGRES_PASSWORD_LITEREV}

FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}

DOCKER_VOLUME_CONTAINER_PATH=${DOCKER_VOLUME_CONTAINER_PATH}
STATIC_ROOT=${STATIC_ROOT}
LITEREV_CACHE_DIR=${LITEREV_CACHE_DIR}

OPENAI_API_KEY=${OPENAI_API_KEY}

ALLOWED_HOSTS=${ALLOWED_HOSTS}
DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

MEDIA_ROOT=${MEDIA_ROOT}
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}

USE_CONTAINER=${USE_CONTAINER}
DOCKER_CPU_LIMIT=${DOCKER_CPU_LIMIT}
DOCKER_CPU_RESERVATION=${DOCKER_CPU_RESERVATION}

GUNICORN_WORKERS=${GUNICORN_WORKERS}

CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}

ES_HOST_URL=${ES_HOST_URL}
ES_USERNAME=${ES_USERNAME}
ES_PASSWORD=${ES_PASSWORD}

CELERY_BROKER=${CELERY_BROKER}
CELERY_BACKEND=${CELERY_BACKEND}

NUMBER_ARTICLE_BY_PAGE=${NUMBER_ARTICLE_BY_PAGE}
NUMBER_THREADS_ALLOWED=${NUMBER_THREADS_ALLOWED}
NUMBER_TRIALS=${NUMBER_TRIALS}
UPDATE_INTERVAL=${UPDATE_INTERVAL}
