ENV=${ENV}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB_LITEREV=${POSTGRES_DB_LITEREV}
POSTGRES_USER_LITEREV=${POSTGRES_USER_LITEREV}
POSTGRES_PASSWORD_LITEREV=${POSTGRES_PASSWORD_LITEREV}

FRONTEND_HOST_ADDRESS=${FRONTEND_HOST_ADDRESS}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}

DOCKER_VOLUME_CONTAINER_PATH=${DOCKER_VOLUME_CONTAINER_PATH}
LITEREV_LOG_CONTAINER_PATH=${LITEREV_LOG_CONTAINER_PATH}
STATIC_ROOT=${STATIC_ROOT}

OPENAI_API_KEY=${OPENAI_API_KEY}

ALLOWED_HOSTS=${ALLOWED_HOSTS}
DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

HOST_DJANGO_MEDIA_ROOT=${HOST_DJANGO_MEDIA_ROOT}
DJANGO_MEDIA_ROOT=${DJANGO_MEDIA_ROOT}

USE_CONTAINER=${USE_CONTAINER}

LITEREV_TASKS_HOST_PORT=${LITEREV_TASKS_HOST_PORT}

GUNICORN_WORKERS=${GUNICORN_WORKERS}

CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}

ES_HOST_URL=${ES_HOST_URL}
ES_USERNAME=${ES_USERNAME}
ES_PASSWORD=${ES_PASSWORD}

CELERY_BROKER=${CELERY_BROKER}
CELERY_BACKEND=${CELERY_BACKEND}

NUMBER_ARTICLE_BY_PAGE=${NUMBER_ARTICLE_BY_PAGE}
NUMBER_THREADS_ALLOWED=${NUMBER_THREADS_ALLOWED}
NUMBER_TRIALS=${NUMBER_TRIALS}
UPDATE_INTERVAL=${UPDATE_INTERVAL}
FRONTEND_HOST_ADDRESS=${FRONTEND_HOST_ADDRESS}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
ORCID_APP_ID=${ORCID_APP_ID}
ORCID_APP_SECRET=${ORCID_APP_SECRET}
ORCID_BASE_DOMAIN=${ORCID_BASE_DOMAIN}

USE_CONTAINER=${USE_CONTAINER}
