backend: bash
env-file: .env
groups:
  clean:
    tasks:
      all:
        help: remove build artifacts, compiled files, and cache
        backend: bash
        run: |
          find . -name '*.egg-info' -exec rm -rf {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name '*.pyo' -exec rm -f {} +
          find . -name '__pycache__' -exec rm -rf {} +
          find . -name '*~' -exec rm -f {} +
          rm -rf build/
          rm -rf dist/
          rm -rf .eggs/
          rm -f .coverage
          rm -rf htmlcov/
          rm -rf .pytest_cache
          rm -rf .mypy_cache
          rm -rf .ruff_cache

  tests:
    tasks:
      lint:
        help: Run linter tools
        hooks:
          pre-run:
            - task: clean.all
        run: |
          pre-commit install
          pre-commit run --all-files --verbose

      coverage-report:
        help: Generate coverage report
        env-file: ./.env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
          SUGAR_ENV: test
        run: |
          coverage report -m --skip-empty

      unit:
        help: Run tests
        args:
          path:
            help: Specify the python module used for the test
            type: string
            default: ""
          params:
            help: Specify parameters to be used for tests
            type: string
            default: "-vvv"
          clean-cov:
            help: Coverage append flag
            type: bool
            action: store_true
        env-file: ./.env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
          SUGAR_ENV: test
        run: |
          rm -rf /tmp/rago
          sugar compose-ext start --options -d

          COVERAGE_FLAG=${{ "--cov-append" if not args.clean_cov else "" }}
          # note: we should increase cov-fail-under to 85!
          COVERAGE_FLAG="${COVERAGE_FLAG} --cov-fail-under=35"
          COVERAGE_FLAG="${COVERAGE_FLAG} --cov-report term-missing"
          COVERAGE_FLAG="${COVERAGE_FLAG} --no-cov-on-fail"

          pytest --cov=. $COVERAGE_FLAG \
            --ds=config.settings.test ${{ args.params }} ${{ args.path }}

  django:
    tasks:
      collectstatic:
        help: Run the collectstatic for the literev service
        run: |
          CMD="python manage.py collectstatic --no-input"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            sugar compose run --service literev --options "--rm" --cmd "$CMD"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            $CMD
          fi

      create-superuser:
        args:
          email:
            help: Specify the username
            type: string
            required: True
            interactive: True
          username:
            help: Specify the username
            type: string
            required: True
            interactive: True
          password:
            help: Specify the password
            type: string
            required: True
            interactive: True
        env:
          POSTGRES_HOST: localhost
        help: create an admin user
        run: |
          export DJANGO_SUPERUSER_PASSWORD=${{ args.password }}
          export DJANGO_SUPERUSER_USERNAME=${{ args.username }}
          CMD="python manage.py createsuperuser --noinput --email ${{ args.email }}"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            SUGAR_FLAGS="--rm --env DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD"
            SUGAR_FLAGS="${SUGAR_FLAGS} --env DJANGO_SUPERUSER_USERNAME=$DJANGO_SUPERUSER_USERNAME"
            sugar compose run --service literev --cmd "$CMD" --options "${SUGAR_FLAGS}"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            $CMD
          fi

      makemigrations:
        help: Run django makemigrations command (just for development)
        args:
          check:
            help: |
              Just check if the latest migration files were already created.
            type: bool
            action: store_true
        run: |
          sugar compose-ext start \
            --services literev-postgres --options -d

          CWD=$(pwd)
          CMD_FLAG="${{ '--check' if args.check else '' }} --no-input"

          for app in 'literev'; do
            echo -e "\nMaking migration files for: '${app}' ...\n"

            CMD="python manage.py makemigrations ${CMD_FLAG} ${app}"

            if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
              sugar compose run --service literev --options "--rm" --cmd "$CMD"
            else
              cd "${CWD}/src/"
              export POSTGRES_HOST=localhost
              $CMD
            fi
          done

          echo "[II] literev-postgres is running."

      migrate:
        help: Migrate regarding to the current migration files
        env-file: .env
        run: |
          sugar compose-ext start \
            --services literev-postgres --options -d

          CMD="python manage.py migrate --no-input"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            sugar compose run --service literev --options "--rm" --cmd "$CMD"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            $CMD
          fi
          echo "[II] literev-postgres is running."

      runserver:
        help: Run the django application directly in the host
        env-file: .env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
        run: |
          sugar --group dev-host compose-ext restart --options "-d"
          pushd src
            python manage.py runserver_plus 0.0.0.0:8000
          popd

      fill-order-clusters:
        help: Fill order cluster in Cluster object DB
        env-file: .env
        run: |
          sugar compose-ext start \
            --services literev-postgres --options -d

          CMD="python manage.py fill_order_cluster"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            sugar compose run --service literev --options "--rm" --cmd "$CMD"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            $CMD
          fi
          echo "[II] Filling order clusters is done."

      count-tokens:
        help: |
          Count tokens for the specified project ID.
          e.g. makim django.count-tokens --project-id 1
        env-file: .env
        args:
          project-id:
            help: |
              The ID of the project for which to count tokens..
            type: string
            default: "1"
            required: true
        run: |
          sugar compose-ext start \
            --services literev-postgres --options -d

          CMD="python manage.py count_tokens --project-id ${{ args.project_id }}"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            sugar compose run --service literev --options "--rm" --cmd "$CMD"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            $CMD
          fi
          echo "[II] Token counting completed for project ID ${{ args.project_id }}."

      optimize-documents:
        help: Run the optimization of the documents
        env-file: .env
        run: |
          sugar compose-ext start \
            --services literev-postgres --options -d

          CMD="python manage.py optimize_documents"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            sugar compose run --service literev --options "--rm" --cmd "$CMD"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            $CMD
          fi
          echo "[II] The optimization of the documents is done."

      fetch-documents:
        help: Run the optimization of the documents
        env-file: .env
        run: |
          sugar compose-ext start \
            --services literev-postgres --options -d

          CMD="python manage.py fetch_documents"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            sugar compose run --service literev --options "--rm" --cmd "$CMD"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            $CMD
          fi
          echo "[II] Access to DB granted."

      optimize-documents-local:
        help: Run the optimization of the documents (temporary)
        env-file: .env
        run: |
          export POSTGRES_HOST=localhost
          cd ./src/
          python manage.py optimize_documents
          echo "[II] The optimization of the documents is done."

      notebook:
        help: Run the django environment in a jupyter notebook
        env-file: .env
        run: |
          export POSTGRES_HOST=localhost
          python src/manage.py shell_plus --lab

      shell:
        help: Run the Django console interpreter inside the container.
        env-file: .env
        env:
          POSTGRES_HOST: localhost
          REDIS_HOST: localhost
        run: |
          sugar compose-ext start --services literev-postgres --options "-d"
          python src/manage.py shell

  containers:
    tasks:
      wait:
        args:
          timeout:
            help: Specify the timeout for waiting the services
            type: string
            default: "90"
          service:
            help: Specify the service to be awaited
            type: string
            required: true
        run: timeout ${{ args.timeout }} ./containers/healthcheck.sh ${{ args.service }}

      wait-all:
        help: wait for all services
        run: |
          makim containers.wait --service literev-postgres
          makim containers.wait --service literev

      host-setup:
        help: Prepare the host for running the containers
        env-file: .env
        run: |
          mkdir -p ${LITEREV_CACHE_DIR}
          mkdir -p ${CONTAINER_VOLUME_DATA_DIR}
          mkdir -p ${POSTGRES_DATA}
          mkdir -p ${POSTGRES_HOST_BACKUP}
          mkdir -p ${STATIC_ROOT}
          sudo chown -R ${HOST_UID}:${HOST_GID} ${STATIC_ROOT}

      postgres-dump-database:
        backend: bash
        args:
          path:
            help: Specify the path for the backup
            type: string
            required: false
            default: "/opt/data/literev/backup"
          dump-name:
            help: Specify the name for the dump file
            type: string
            required: false
            default: "literev-legal-$(date +%d-%m-%y_%H-%M)"
        run: |
          echo "Generating dump file...'"
          PGPASSWORD="${{ env.POSTGRES_PASSWORD }}" \
          CMD="bash -c 'pg_dumpall -p ${{ env.POSTGRES_PORT }} -U ${{ env.POSTGRES_USER }} | gzip > ${{ args.path }}/${{ args.dump_name }}.sql.gz'"
          sugar compose exec --service literev-postgres --cmd "${CMD}"
          echo "Output dump file: ${{ args.path }}/${{ args.dump_name }}"

          if [[ $? -eq 0 ]]; then
              echo "Database dumped successfully"
          else
              echo "Failed to dump database."
              exit 1
          fi

      postgres-restore-database:
        backend: bash
        args:
          path:
            help: Specify the path for the backup
            type: string
            required: false
            default: "/opt/data/literev/backup"
          dump-name:
            help: Specify the name for the dump file
            type: string
            required: false
            default: "literev-legal-$(date +%d-%m-%y_%H-%M).sql.gz"
          drop-all:
            help: Specify if the database should be dropped before restoring
            type: string
            required: True
        run: |
          # grep -vE "CREATE ROLE postgres|ALTER ROLE postgres" "${path_file}" > \
          # "${{ args.path }}/pre_${{ args.dump_name }}.sql"

          echo "Getting dump file: '${{ args.path }}/${{ args.dump_name }}'"
          CMD="bash -c 'gunzip -c ${{ args.path }}/${{ args.dump_name }} > ${{ args.path }}/${{ args.dump_name }}.sql'"
          sugar compose exec --service literev-postgres --cmd "${CMD}"

          if [ "${{ args.drop_all }}" = "true" ]; then
            echo "Dropping existing roles and database..."
            sugar compose exec --service literev-postgres --cmd bash -c \
            'psql -v ON_ERROR_STOP=1 --host=localhost -U ${{ env.POSTGRES_USER }} -p ${{ env.POSTGRES_PORT }} -c \
            "DROP DATABASE IF EXISTS literev;"'
            sugar compose exec --service literev-postgres --cmd bash -c \
            'psql -v ON_ERROR_STOP=1 --host=localhost -U ${{ env.POSTGRES_USER }} -p ${{ env.POSTGRES_PORT }} -c \
            "DROP OWNED BY literev CASCADE; DROP ROLE IF EXISTS literev;"'
          fi

          echo "Restoring database..."
          CMD="bash -c 'cat ${{ args.path }}/${{ args.dump_name }}.sql | "
          CMD="${CMD} psql -v -U ${{ env.POSTGRES_USER }} -p ${{ env.POSTGRES_PORT }} -d postgres'"
          sugar compose exec --service literev-postgres --cmd "${CMD}"

          if [[ $? -eq 0 ]]; then
              echo "Database restored successfully."
          else
              echo "Failed to restore database."
              exit 1
          fi

  nginx:
    tasks:
      proxydomain:
        help: Create SSL proxy configuration with CertBot for a domain
        env-file: .env
        run: |
          python ./containers/nginx/scripts/generate_proxy_ui.py
      generate-certificate:
        help: Generate certificate
        run: |
          ./scripts/generate-certificates.sh
      setup:
        hooks:
          pre-run:
            - task: clean.all
            - task: nginx.proxydomain
            - task: nginx.generate-certificate

  elasticsearch:
    tasks:
      index-json:
        help: Load normalized sample data to Elasticsearch
        env-file: .env
        args:
          index-name:
            help: Specify the index name
            type: string
            required: false
            default: "test_judiciary"
          raw-json:
            help: Specify the original JSON file path
            type: string
            required: false
            default: "/opt/data/json_raw/output.json"
          path-json:
            help: Specify the final JSON file path
            type: string
            required: false
            default: "/opt/data/json_raw/"
          final-json:
            help: Specify the final JSON file path
            type: string
            required: false
            default: ""
        # env:
        #   TIMESTAMP: '$(date +"%Y%m%d")'
        backend: bash
        run: |
          export timestamp=$(date +"%Y%m%d")
          echo ${timestamp}

          final_json="${{ args.path_json }}${{ args.index_name }}_$(basename "${{ args.raw_json }}" .json)_${timestamp}.json"
          python scripts/elasticsearch_loader.py load-data \
           -i "${{ args.index_name }}" \
           -r "${{ args.raw_json }}" \
           -f "$final_json"

      count-docs-in-index:
        help: |
          Download data from BioRxiv/MedRxiv API within a specified date range.
        args:
          index-name:
            help: Specify the index name (e.g., 'biorxiv' or 'medrxiv')
            type: string
            required: true
        backend: bash
        run: |
          python scripts/elasticsearch_loader.py count-documents ${{ args.index_name }}

      process-documents:
        help: Load processed documents into the database
        env-file: .env
        args:
          index-name:
            help: Specify the index name
            type: string
            required: true
          search-term:
            help: Specify the search term
            type: string
            required: true
          username:
            help: Specify the username
            type: string
            required: true
          date-start:
            help: Specify the start date
            type: string
            required: false
            default: "1900-01-01"
          date-end:
            help: Specify the end date
            type: string
            required: false
        backend: bash
        run: |
          # Ensure default values for date_end if not provided
          DATE_END="${{ args.date_end }}"
          if [[ -z "$DATE_END" || "$DATE_END" == "None" ]]; then
            DATE_END=$(date +'%Y-%m-%d')
          fi

          # Construct the command to avoid extra quotes being added
          CMD="python manage.py process_corpus\
            --index-name ${{ args.index_name }}\
            --search-term ${{ args.search_term }}\
            --username ${{ args.username }}\
            --start-date ${{ args.date_start }}\
            --end-date $DATE_END"

          echo "Executing command: $CMD"

          if [[ "${{ env.USE_CONTAINER }}" == "true" ]]; then
            sugar run --service literev --options "--rm" --cmd "$CMD"
            echo "Started indexing for index ${{ args.index_name }} with date range ${{ args.date_start }} - $DATE_END"
          else
            cd ./src/
            export POSTGRES_HOST=localhost
            export ES_HOST_URL=http://localhost:9200
            eval "$CMD"
          fi

  release:
    vars:
      app: |
        npx --yes \
          -p semantic-release \
          -p conventional-changelog-conventionalcommits \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "semantic-release-replace-plugin@1.2.7" \
          semantic-release

    tasks:
      ci:
        help: run semantic release on CI
        run: ${{ vars.app }} --ci

      dry:
        help: run semantic release in dry-run mode
        run: |
          ${{ vars.app }} --dry-run
