backend: compose
env-file: .env
defaults:
  profile: ${{ env.SUGAR_ENV or env.ENV or "dev" }}
  project-name: literev-legal${{ env.DOCKER_PROJECT_NAME }}

hooks:
  pre-run:
    - name: collectstatic
      targets:
        compose:
          - build
          - start
          - restart
          - up
        compose-ext:
          - build
          - start
          - restart
          - up
      run: |
        makim django.collectstatic

profiles:
  prod:
    config-path:
      - containers/compose.base.yaml
      - containers/compose.prod.yaml
      - containers/compose.elasticsearch.yaml
    env-file: .env
    services:
      default:
        - literev
        - literev-postgres
        - literev-redis
        - literev-celery
        - literev-nginx
        - certbot
      available:
        - name: literev
        - name: literev-postgres
        - name: literev-redis
        - name: literev-celery
        - name: literev-nginx
        - name: certbot
        - name: es-legal-setup
        - name: es-restore
        - name: es-legal-1
        - name: es-legal-2
        - name: es-legal-3

  dev:
    config-path:
      - containers/compose.base.yaml
      - containers/compose.dev.yaml
      - containers/compose.elasticsearch.yaml
      - containers/compose.jupyter.yaml
    env-file: .env
    services:
      default:
        - literev
        - literev-postgres
        - literev-redis
        - literev-celery
      available:
        - name: literev
        - name: literev-postgres
        - name: literev-redis
        - name: literev-celery
        - name: literev-elasticsearch
        - name: literev-jupyter

  dev-host:
    config-path:
      - containers/compose.base.yaml
      - containers/compose.dev.yaml
    env-file: .env
    services:
      default:
        - literev-postgres
        - literev-redis
        - literev-celery
      available:
        - name: literev-postgres
        - name: literev-redis
        - name: literev-celery

  test:
    config-path:
      - containers/compose.base.yaml
      - containers/compose.dev.yaml
    env-file: .env
    services:
      default:
        - literev-postgres
        - literev-redis
      available:
        - name: literev-postgres
        - name: literev-redis
