version: 1.0
compose-app: docker compose
env-file: .env
defaults:
  group: {{ env.ENV }}
  project-name: literev-legal{{ env.DOCKER_PROJECT_NAME }}
groups:
  prod:
    compose-path:
      - containers/compose.base.yaml
      - containers/compose.prod.yaml
    env-file: .env
    services:
      default: literev,literev-postgres,literev-redis,literev-celery,literev-nginx,certbot
      available:
        - name: literev
        - name: literev-postgres
        - name: literev-redis
        - name: literev-celery
        - name: literev-nginx
        - name: certbot

  dev:
    compose-path:
      - containers/compose.base.yaml
      - containers/compose.dev.yaml
    env-file: .env
    services:
      default: literev,literev-postgres,literev-redis,literev-celery
      available:
        - name: literev
        - name: literev-postgres
        - name: literev-redis
        - name: literev-celery
