# Generated by Django 5.0.4 on 2024-04-05 19:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=8196)),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('decision_date', models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True)),
                ('procedure_type', models.CharField(default='', max_length=256)),
                ('descriptors', models.TextField(blank=True, default='', null=True)),
                ('standards', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('raw_document_id', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('raw_document_text', models.TextField(blank=True, default='', null=True)),
                ('preprocessed_document', models.TextField(blank=True, default='', null=True)),
                ('procedure_year', models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=256)),
                ('creation_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('query', models.CharField(max_length=4096)),
                ('range_begin_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('range_end_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('total_documents', models.IntegerField(default=0)),
                ('step', models.CharField(default='getting_documents', max_length=256)),
                ('step_number', models.IntegerField(default=0)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('best_dbcv', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.cluster')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.project'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.project'),
        ),
    ]
