# Generated by Django 5.0.4 on 2024-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prepared_for_ngrams',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
