# Generated by Django 5.0.6 on 2024-07-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0005_add_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_task_code',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
