# Generated by Django 5.0.7 on 2024-09-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0006_project_actual_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
