# Generated by Django 5.0.7 on 2024-09-30 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0007_cluster_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRefinement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('filters', models.JSONField(default=dict)),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='literev.projectrefinement')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.project')),
            ],
        ),
        migrations.CreateModel(
            name='RefinementIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_documents', models.IntegerField(default=0)),
                ('checked_documents_ids', models.JSONField(default=list)),
                ('excluded_documents_ids', models.JSONField(default=list)),
                ('new_neighbors_ids', models.JSONField(default=list)),
                ('result_documents_ids', models.JSONField(default=list)),
                ('parent_iteration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='literev.refinementiteration')),
                ('refinement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literev.projectrefinement')),
            ],
        ),
    ]
