# Generated by Django 5.0.7 on 2024-10-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0009_tablechoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_indices',
            field=models.JSONField(default=list),
        ),
    ]
