# Generated by Django 5.1.2 on 2024-11-19 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0011_alter_document_standards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress')], default='in-progress', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_rags', to='literev.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocumentRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField()),
                ('answer', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_rags', to='literev.document')),
                ('project_rag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='literev.projectrag')),
            ],
        ),
    ]
