# Generated by Django 5.1.3 on 2024-12-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0012_projectrag_projectdocumentrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechoice',
            name='is_check',
            field=models.BooleanField(null=True),
        ),
    ]
