# Generated by Django 5.1.4 on 2025-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0013_alter_tablechoice_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chamber',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
