# Generated by Django 5.1.3 on 2025-01-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0014_document_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='natural_language_query',
            field=models.CharField(blank=True, default='', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='projectrag',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress'), ('failed', 'Failed')], default='in-progress', max_length=20),
        ),
    ]
