# Generated by Django 5.1.5 on 2025-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0015_project_natural_language_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrag',
            name='summary_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
