# Generated by Django 5.1.5 on 2025-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0017_projectragstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocumentrag',
            name='confidence_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
