# Generated by Django 5.1.5 on 2025-04-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0018_projectdocumentrag_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocumentrag',
            name='citation_context',
            field=models.JSONField(default=list),
        ),
    ]
