# Generated by Django 5.1.5 on 2025-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0019_projectdocumentrag_citation_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrag',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('questioning_documents', 'Generating Answers'), ('generating_scores', 'Scoring Answers'), ('generating_summary', 'Creating General Summary'), ('generating_statistics', 'Generating Statistics'), ('tagging_considerations', 'Tagging Considerations'), ('completed', 'Completed'), ('failed', 'Failed')], default='in-progress', max_length=30),
        ),
    ]
