# Generated by Django 5.1.5 on 2025-05-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0020_alter_projectrag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrag',
            name='num_documents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectrag',
            name='valid_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
