# Generated by Django 5.2.7 on 2025-10-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0021_projectrag_num_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='record_key',
            field=models.CharField(blank=True, default='no-record-key', max_length=256, null=True),
        ),
    ]
