# Generated by Django 5.2.9 on 2026-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0022_document_record_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_html_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
