# Generated by Django 5.2.9 on 2026-01-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literev', '0023_document_document_html_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='elastic_search_query',
            field=models.JSONField(default=dict),
        ),
    ]
