services:
  literev-base:
    # TODO(#113): Consider refactoring the Dockerfile to avoid creating directories
    # during the build process. This can lead to unnecessary layers and
    # image size. Instead, create these directories at runtime or in the
    # entrypoint script to ensure they are always created when needed.
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: containers/literev/Dockerfile
      args:
        # note: if you want to use a specific UID and GID, ensure to add it to
        #       the .env file
        - UID=${HOST_UID:-1000}
        - GID=${HOST_GID:-1000}
        - ENV=${ENV:-prod}
        - CONTAINER_VOLUME_DATA_DIR=${CONTAINER_VOLUME_DATA_DIR}
        - STATIC_ROOT=${STATIC_ROOT:-/tmp/literev/static}
        - MEDIA_ROOT=${DJANGO_MEDIA_ROOT:-/tmp/literev/media}
        - HTTP_PROXY=${http_proxy}
        - HTTPS_PROXY=${https_proxy}
    user: "literev:literev"


  literev:
    extends: literev-base
    hostname: literev
    env_file:
      - ../.env
    environment:
      DJANGO_PORT: 8000
    ports:
      - ${FRONTEND_HOST_PORT}:8000
    depends_on:
      - literev-postgres
    volumes:
      - container_data_dir:${CONTAINER_VOLUME_DATA_DIR}
      - static_root:${STATIC_ROOT:-/tmp/literev/static}
      - media_root:${DJANGO_MEDIA_ROOT:-/tmp/literev/media}
    networks:
      - literev
    healthcheck:
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 40s  # requires docker-compose 3.4
      test: ["CMD", "curl", "-f", "http://localhost:${DJANGO_PORT:-8000}/status/"]

  literev-postgres:
    hostname: literev-postgres
    # restart: unless-stopped
    build:
      context: ..
      dockerfile: containers/postgresql/Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    env_file:
      - ../.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - literev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: postgres -p ${POSTGRES_PORT}

  literev-celery:
    extends: literev-base
    hostname: literev-celery
    build:
      context: ..
      dockerfile: containers/literev/Dockerfile
    command: celery --app=config worker --loglevel=INFO  --concurrency=${CELERY_WORKER_CONCURRENCY}
    env_file:
      - ../.env
    depends_on:
      - literev-redis
      - literev-postgres
    volumes:
      - container_data_dir:${CONTAINER_VOLUME_DATA_DIR}
      - static_root:${STATIC_ROOT:-/tmp/literev/static}
      - media_root:${DJANGO_MEDIA_ROOT:-/tmp/literev/media}
    networks:
      - literev

  literev-redis:
    image: redis:7-alpine
    hostname: literev-redis
    networks:
      - literev
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 1024M

  literev-jupyter:
    user: "${HOST_UID}:${HOST_GID}"
    extends: literev-base
    hostname: literev-jupyter
    command: jupyter lab --ip=0.0.0.0 --allow-root \
             --NotebookApp.token='${JUPYTER_TOKEN}' \
             --NotebookApp.password='' \
             --NotebookApp.base_url=/jupyter \
             --NotebookApp.allow_origin='*' \
             --NotebookApp.allow_remote_access=True
    ports:
      - "8888:8888"
    env_file:
      - ../.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      PYTHONPATH: /opt/services/literev/src
    volumes:
      - container_data_dir:${CONTAINER_VOLUME_DATA_DIR}
      - static_root:${STATIC_ROOT:-/tmp/literev/static}
      - media_root:${DJANGO_MEDIA_ROOT:-/tmp/literev/media}
    networks:
      - literev
    depends_on:
      - literev-postgres
      - literev-redis



volumes:
  container_data_dir:
  static_root:
  media_root:

networks:
  literev:

# NETWORKS
# networks allows services to resolve composeother services
# by their hostnames example: literev, literev-postgres, etc.
# server literev:8000; resolves to server  xxx.x.x.x:8000;
