version: '3.9'

services:
  literev:
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DEBUG: 1
    volumes:
      - ../src/:/opt/services/literev/src/

  literev-celery:
    environment:
      DEBUG: 1
    volumes:
      - ../src/:/opt/services/literev/src/

  literev-postgres:
    environment:
      DEBUG: 1
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata_volume:/var/lib/postgresql/data

volumes:
  container_data_dir:
  pgdata_volume:
    external: false
