services:
  literev-jupyter:
    user: "${HOST_UID}:${HOST_GID}"
    hostname: literev-jupyter
    command: >
      jupyter lab --ip=0.0.0.0 --allow-root
      --NotebookApp.token='${JUPYTER_TOKEN}'
      --NotebookApp.password=''
      --NotebookApp.base_url=/jupyter
      --NotebookApp.allow_origin='*'
      --NotebookApp.allow_remote_access=True
    ports:
      - "8888:8888"
    env_file:
      - ../.env
    working_dir: ${LITEREV_NOTEBOOKS_DIR}
    environment:
      ENV: dev
      DJANGO_SETTINGS_MODULE: config.settings.dev
      PYTHONPATH: /opt/services/literev/src
    volumes:
      - jupyter_notebook:${LITEREV_NOTEBOOKS_DIR}
    networks:
      - literev
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8888/jupyter/api/sessions?token=${JUPYTER_TOKEN}"]
      interval: 10s
      timeout: 3s
      retries: 12

volumes:
  jupyter_notebook:
    external: false
