POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PASSWORD_LITEREV=${POSTGRES_PASSWORD_LITEREV}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_USER_LITEREV=${POSTGRES_USER_LITEREV}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_DB_LITEREV=${POSTGRES_DB_LITEREV}
