[build-system]
requires = ["setuptools>=70.1.0,<80.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lr-search"
version = "0.12.0"  # semantic-release
description = "Elasticsearch collection and metadata extraction for literev."
readme = "README.md"
requires-python = ">=3.11,<3.12"
authors = [
  {name = "Aziza", email = "FatmaAziza.Merzouki@unige.ch"},
  {name = "Erol", email = "Erol.Orel@unige.ch"},
  {name = "Ivan Ogasawara", email = "ivan.ogasawara@gmail.com"},
]
dependencies = [
  "lr-contracts == 0.12.0",
  "lr-query == 0.12.0",
  "elasticsearch >=8.12.1,<9.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["lr_search*"]

[tool.setuptools.package-data]
lr_search = [
  "py.typed",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
python_files = ["tests.py", "test_*.py"]
