"""
Django settings for literev legal project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from __future__ import annotations

import logging
import multiprocessing as mp
import os

from pathlib import Path
from urllib.parse import quote

import django_stubs_ext
import environ

django_stubs_ext.monkeypatch()

# Ensure that logging captures warnings issued by warnings.warn()
logging.captureWarnings(True)

ROOT_DIR = Path(__file__).resolve().parent.parent.parent.parent.parent

# Ensure that warnings are enabled
os.environ["PYTHONWARNINGS"] = "default"

env = environ.Env()

SERVICE_NAME = "literev"

# PaCMAP imports Numba-compiled functions with caching enabled. Some container
# and editable-install environments do not provide a usable package-local cache
# locator, so make the cache explicit before PaCMAP can be imported.
os.environ["NUMBA_CACHE_DIR"] = (
    os.environ.get("NUMBA_CACHE_DIR") or "/tmp/literev/numba-cache"
)
NUMBA_CACHE_DIR = Path(os.environ["NUMBA_CACHE_DIR"])
NUMBA_CACHE_DIR.mkdir(parents=True, exist_ok=True)

# HTTP redirect is issued to the same URL
APPEND_SLASH = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# === env variables ===

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

DEBUG = env.bool("DEBUG", default=False)

# Get OpenAI API key
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

HACTAR_API_KEY = os.environ.get("HACTAR_API_KEY", "")

USE_HACTAR_LLM = env.bool("USE_HACTAR_LLM", default=False)

USE_HACTAR_LLM_FOR_BOOLEAN_QUERY = env.bool(
    "USE_HACTAR_LLM_FOR_BOOLEAN_QUERY", default=False
)

HACTAR_BASE_URL = os.environ.get("HACTAR_BASE_URL", "https://hactar.unige.ch")

HACTAR_VERIFY_SSL = env.bool("HACTAR_VERIFY_SSL", default=False)

HACTAR_BOOLEAN_QUERY_MODEL = os.environ.get(
    "HACTAR_BOOLEAN_QUERY_MODEL", "mistral-small3.1:24b"
)

# Hactar embedding model served by the Ollama gateway
# (``{HACTAR_BASE_URL}/ollama/api/embed``). ``mxbai-embed-large`` returns
# ~1024-dim vectors — a different vector space than OpenAI
# ``text-embedding-3-large`` (3072-dim), so a Chroma collection embedded with
# Hactar must also be *queried* with Hactar (see ``SECTION_EMBED_ENGINE``).
HACTAR_EMBED_MODEL = os.environ.get(
    "HACTAR_EMBED_MODEL", "mxbai-embed-large:latest"
)

# Default embedding engine for the federal section collections. Defaults to
# "openai" so the federal courts are embedded with the *exact same* pipeline as
# the Geneva chambers (``text-embedding-3-large``, 3072-dim, one shared vector
# space). Set ``FEDERAL_EMBED_ENGINE=hactar`` to embed them near-free with
# Hactar (``mxbai-embed-large``, ~1024-dim) instead — build
# (``run_chromadb_embeddings``) and query time both read ``SECTION_EMBED_ENGINE``
# below, so switching the engine keeps them consistent.
FEDERAL_EMBED_ENGINE = os.environ.get("FEDERAL_EMBED_ENGINE", "openai")

# Per-source embedding engine ("openai" | "hactar") for section-based Chroma
# collections. Anything not listed defaults to "openai" (see
# ``literev.libs.chroma_utils.get_section_embed_engine``).
SECTION_EMBED_ENGINE = {
    "chambre_administrative": "openai",
    "chambre_penale": "openai",
    "chambre_civile": "openai",
    "bundesgericht": FEDERAL_EMBED_ENGINE,
    "bundesverwaltungsgericht": FEDERAL_EMBED_ENGINE,
    "bundesstrafgericht": FEDERAL_EMBED_ENGINE,
}

CHAT_MODEL = os.environ.get("CHAT_MODEL", "gpt-4.1-mini")

# --- Retrieval reranking -----------------------------------------------------
# Optional cross-encoder reranking of the lexical (BM25) candidate set from
# Elasticsearch. Disabled by default: with RERANK_ENABLED=False the BM25 order
# is used unchanged, so this is a no-op until a reranker is configured. When
# enabled, the top RERANK_TOP_K candidates are reordered by relevance to the
# natural-language query; any reranker error degrades gracefully to BM25 order.
# Parsed with plain ``os.environ`` + explicit empty-string fallbacks rather
# than ``env.int``/``env.bool``: the deployment renders ``.env`` from
# ``.env.tpl``, so an unset variable arrives as an *empty string*
# (``RERANK_TOP_K=``) — which ``env.int`` rejects (``invalid literal for
# int()``), taking the whole settings module (and every test job) down with it.


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name, "").strip()
    try:
        return int(raw) if raw else default
    except ValueError:
        return default


RERANK_ENABLED = os.environ.get("RERANK_ENABLED", "").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
# "local"  = a self-hosted cross-encoder exposing a TEI-style POST /rerank
#            (recommended: BAAI/bge-reranker-v2-m3 via HuggingFace
#            Text Embeddings Inference, on the VM — multilingual, on-prem,
#            no per-query cost). "cohere" = the Cohere Rerank API.
RERANKER_PROVIDER = os.environ.get("RERANKER_PROVIDER", "").strip() or "local"
RERANKER_URL = (
    os.environ.get("RERANKER_URL", "").strip() or "http://literev-reranker:80"
)
RERANKER_MODEL = (
    os.environ.get("RERANKER_MODEL", "").strip() or "rerank-multilingual-v3.0"
)
COHERE_API_KEY = os.environ.get("COHERE_API_KEY", "").strip()
# How many BM25 candidates to rerank, how much of each decision to send to the
# cross-encoder (it truncates ~512 tokens anyway), and the request timeout.
RERANK_TOP_K = _env_int("RERANK_TOP_K", 50)
RERANK_MAX_CHARS = _env_int("RERANK_MAX_CHARS", 2000)
RERANKER_TIMEOUT_S = _env_int("RERANKER_TIMEOUT_S", 20)

APP_NAME = "literev"
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "literev",
    *env("ALLOWED_HOSTS", default="").split(","),
]

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

THIRD_PARTY_APPS: list[str] = [
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
]

LOCAL_CONFIG_APP = ["literev.apps.LiterevConfig"]

LOCAL_APPS = [
    "literev",
]
# LOCAL_APPS must come before THIRD_PARTY_APPS to ensure that our
# custom templates override the default templates
# provided by django-allauth.
INSTALLED_APPS = LOCAL_APPS + DJANGO_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            str(BASE_DIR / "templates")
        ],  # TODO: Check if this should point to /src/backend/literev/templates/
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": True,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.settings_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("POSTGRES_DB_LITEREV", "literev"),
        "USER": os.environ.get("POSTGRES_USER_LITEREV", "literev"),
        # No secret default: the password must come from the environment
        # (local .env or a CI/deploy secret). Never ship a credential in source.
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD_LITEREV", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "literev-postgres"),
        "PORT": os.environ.get("POSTGRES_PORT", "35432"),
    }
}


def get_database_uri():
    """
    Constructs the database URI from environment variables.

    Returns
    -------
    str
        A string representing the PostgreSQL database URI.
    """
    db = DATABASES["default"]
    return f"postgresql://{db['USER']}:{db['PASSWORD']}@{db['HOST']}:{db['PORT']}/{db['NAME']}"


DATABASE_URI = get_database_uri()


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
_validation_module = "django.contrib.auth.password_validation"
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": f"{_validation_module}.UserAttributeSimilarityValidator"},
    {"NAME": f"{_validation_module}.MinimumLengthValidator"},
    {"NAME": f"{_validation_module}.CommonPasswordValidator"},
    {"NAME": f"{_validation_module}.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# settings/base.py
import os

REDIS_HOST = os.getenv("REDIS_HOST", "literev-redis")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
REDIS_DB = os.getenv("REDIS_DB", "0")

REDIS_USERNAME = quote(os.getenv("REDIS_USERNAME", "app"), safe="")
REDIS_PASSWORD = quote(os.getenv("REDIS_PASSWORD", ""), safe="")

REDIS_URL = f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL)

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"
CELERY_ACCEPT_CONTENT = ["pickle"]
CELERY_WORKER_CONCURRENCY = os.getenv("CELERY_WORKER_CONCURRENCY", "4")
CELERY_WORKER_POOL_RESTARTS = True


# STATIC / MEDIA
# ------------------------------------------------------------------------------
FRONTEND_BUILD_DIR = ROOT_DIR / "src" / "frontend" / "build"
FRONTEND_STATIC_DIR = FRONTEND_BUILD_DIR / "static"
FRONTEND_ASSET_MANIFEST_PATH = FRONTEND_BUILD_DIR / "asset-manifest.json"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
    ("css", os.path.join(BASE_DIR, "static/css")),
    ("js", os.path.join(BASE_DIR, "static/js")),
    ("images", os.path.join(BASE_DIR, "static/images")),
    ("webfonts", os.path.join(BASE_DIR, "static/webfonts")),
]

if FRONTEND_STATIC_DIR.exists():
    STATICFILES_DIRS.append(str(FRONTEND_STATIC_DIR))
STATIC_ROOT = os.environ.get("STATIC_ROOT") or str(BASE_DIR / "staticfiles")

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


MEDIA_URL = "/media/"

# CONTAINER VOLUMES
# ------------------------------------------------------------------------------
MEDIA_ROOT = env("MEDIA_ROOT", default="/opt/data/literev/static/media")

CONTAINER_VOLUME_DATA_DIR = Path(
    env("CONTAINER_VOLUME_DATA_DIR", default="/opt/data/literev")
)

ARTICLE_DATA = CONTAINER_VOLUME_DATA_DIR / "articles"
PLOT_DATA = CONTAINER_VOLUME_DATA_DIR / "plot"
PKL_DATA = CONTAINER_VOLUME_DATA_DIR / "pkl"

for dir in [
    MEDIA_ROOT,
    CONTAINER_VOLUME_DATA_DIR,
    ARTICLE_DATA,
    PLOT_DATA,
    PKL_DATA,
]:
    os.makedirs(dir, exist_ok=True)

LIMIT_NUMBER_REFINEMENTS = env.int("LIMIT_NUMBER_REFINEMENTS", default=15)
LIMIT_NUMBER_ITERATIONS = env.int("LIMIT_NUMBER_ITERATIONS", default=15)

CLUSTERING_MIN_DOCUMENTS = env.int("CLUSTERING_MIN_DOCUMENTS", default=20)

# DOCUMENTS COLLECTORS
# ------------------------------------------------------------------------------
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000
mp.set_start_method("spawn", True)  # This needs to be set at the program start
NUMBER_THREADS_ALLOWED = env.int(
    "NUMBER_THREADS_ALLOWED", default=mp.cpu_count()
)
NUMBER_TRIALS = env.int("NUMBER_TRIALS", default=10)
NUMBER_OPTUNA_JOBS = env.int("NUMBER_OPTUNA_JOBS", default=5)
NUMBER_ARTICLE_BY_PAGE = env.int("NUMBER_ARTICLE_BY_PAGE", default=30)


# SECURITY
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-httponly
SESSION_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/dev/ref/settings/#csrf-cookie-httponly
CSRF_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-browser-xss-filter
SECURE_BROWSER_XSS_FILTER = True
# https://docs.djangoproject.com/en/dev/ref/settings/#x-frame-options
X_FRAME_OPTIONS = "DENY"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# To sent emails from the webapp in the terminal
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

SITE_ID = 1

LOGIN_REDIRECT_URL = "/search/"
LOGOUT_REDIRECT_URL = "/"

# Allauth configuration
SIGNUP_SECRET_CODE = os.environ.get("SIGNUP_SECRET_CODE", "gXCxdo1")

ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = env(
    "ACCOUNT_EMAIL_VERIFICATION", default="optional"
)
ACCOUNT_SIGNUP_FORM_CLASS = "literev.signup_forms.LegalSignupForm"

DOWNLOAD_PDF_ARTICLE = False

# CACHE CONFIGURATION
LITEREV_CACHE_DIR = Path(
    env("LITEREV_CACHE_DIR", default="/opt/data/literev/cache")
)
CACHE_ACTIVE = env.bool("LITEREV_CACHE_ACTIVE", False)
CACHE_EXPIRATION = 3600  # seconds

MIN_CONFIDENCE = env.float("MIN_CONFIDENCE", default=0.0)

# LOGGING
LOGGING_LEVEL = logging.WARNING

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Log research summary
# see more in workflow.libs.summary_log.py
LOG_RESEARCH_SUMMARY = env.bool("LOG_RESEARCH_SUMMARY", default=False)

# Deactivate all collectors
DEACTIVATE_ALL_COLLECTORS = env.bool(
    "DEACTIVATE_ALL_COLLECTORS", default=False
)

# ELASTICSEARCH
ES_HOST_URL = os.environ.get("ES_HOST_URL")
ES_USERNAME = os.environ.get("ES_USERNAME")
ES_PASSWORD = os.environ.get("ES_PASSWORD")
ES_SSL_CERTS = os.environ.get("ES_SSL_CERTS", default=False)

PROCESS_ALL_CORPUS_QUERY = os.environ.get(
    "PROCESS_ALL_CORPUS_QUERY", default="#PROCESS-ALL-CORPUS-LITEREV-00"
)

LITEREV_CACHE_DIR.mkdir(parents=True, exist_ok=True)

# LITEREV CHAMBERS
LITEREV_CHAMBER_NAMES = [
    "chambre_penale",
    "chambre_civile",
    "chambre_administrative",
    *env("LITEREV_CHAMBER_NAMES", default="").split(","),
]
