from __future__ import annotations

import logging
import random

from typing import cast

import openai
import tiktoken

from django.conf import settings
from openai import OpenAI

from literev.models import Cluster, Document

logger = logging.getLogger(__name__)

openai_client = OpenAI(api_key=settings.OPENAI_API_KEY)

# gpt model consumed by the api
GPT_MODEL = "gpt-4o-mini"
GPT_MODEL_MAX_TOKENS = 128000
MAX_TOKENS_RESPONSE = 250
# 200 tokens extra margin for security
TOKEN_LIMIT = GPT_MODEL_MAX_TOKENS - MAX_TOKENS_RESPONSE - 200
RANDOM_K = 27


def call_chatgpt(prompt: str, api_key: str = settings.OPENAI_API_KEY) -> str:
    """
    Call ChatGPT via the OpenAI Python package.

    Sets the OpenAI API key, sends the prompt to ChatGPT,
    and returns the generated response.

    Parameters
    ----------
    prompt : str
        Input text prompt for ChatGPT.

    api_key : str, optional
        The OpenAI API key. Defaults to project settings.

    Returns
    -------
    str
        Response generated by ChatGPT.

    References
    ----------
    More on ChatGPT: https://platform.openai.com/docs/guides/chat/introduction

    Examples
    --------
    >>> response = call_chatgpt("What is the capital of France?")
    >>> logger.info(response)
    'The capital of France is Paris.'
    """

    messages = [{"role": "user", "content": prompt}]

    try:
        logger.info("Sending request to OpenAI ChatGPT API")
        response = openai_client.chat.completions.create(
            model=GPT_MODEL,
            messages=messages,  # type: ignore
            max_tokens=MAX_TOKENS_RESPONSE,
            temperature=0,
        )
    except openai.RateLimitError as e:
        if settings.DEBUG:
            logger.debug(f"RateLimitError in dev mode: {e}")
            return "RateLimit Error devmode dummy text"
        else:
            # if not in dev mode, log error and return empty string
            logger.error(f"OpenAI API RateLimitError: {e}")
            return ""
    except openai.OpenAIError as e:
        # all other OpenAI api errors will fall here and return an empty string
        logger.error(f"OpenAI API Error:{e}")
        return ""

    return cast(str, response.choices[0].message.content)


def build_prompt(cluster: Cluster) -> str:
    """
    Build a GPT prompt for summarizing a cluster of law cases.

    Constructs a prompt to describe a cluster of law cases based on a predefined
    template. The function collects context from documents associated with the cluster
    and ensures the resulting prompt respects the model's token limit.

    Parameters
    ----------
    cluster : Cluster
        A Cluster object containing the topic and associated documents.

    Returns
    -------
    str
        A complete prompt formatted for GPT consumption.

    Notes
    -----
    - The function selects up to `RANDOM_K` words randomly from each document's preprocessed
      text for inclusion in the prompt.
    - If the token limit (`TOKEN_LIMIT`) is exceeded, additional documents are excluded.
    - Prompts are generated in French and include specific constraints to maintain
      response quality.

    Examples
    --------
    >>> cluster = Cluster.objects.get(id=1)
    >>> prompt = build_prompt(cluster)
    >>> print(prompt)
    """

    prompt_fragments: list[str] = []
    enc = tiktoken.encoding_for_model(GPT_MODEL)

    prompt_template = (
        "Provide a clear and concise general description based on the following "
        "most important keywords: {keywords} from a cluster containing "
        "law cases from the canton of Geneva in Switzerland. The summary must "
        "represent all law cases collectively and not be based only on a single one. "
        "In addition to the most important keywords, use "
        "the following additional context coming from the law cases contained in this cluster:"
        "\n"
    )

    prompt_constraints = (
        "Ensure the response maintains a narrative voice suitable for a general "
        "description while minimizing the use of pronouns. "
        "Avoid: unnecessary introductions and redundancies, using quotes, backticks, "
        "cluster's keywords and names of individuals, and words such as topic, case, "
        "we propose, proposing, we, this report. Summarize in exactly "
        "two sentences, ensuring no redundancy between sentences. "
        "Write the response in French."
    )

    document_context_template = "{context}.\n"

    prompt = prompt_template.format(keywords=cluster.topic)

    documents = Document.objects.filter(clusterelement__cluster=cluster)

    for i, document in enumerate(documents, start=1):
        abstract_words = document.preprocessed_document.split()

        if len(abstract_words) > RANDOM_K:
            rnd_index = random.randrange(len(abstract_words) - RANDOM_K)
            document_abstract = " ".join(
                abstract_words[rnd_index : rnd_index + RANDOM_K]
            )
        else:
            logger.warning(
                f"Document {i} does not have enough abstract words."
            )
            document_abstract = " ".join(abstract_words)

        document_context = document_context_template.format(
            context=document_abstract
        )
        prompt_fragments.append(document_context)

        if (len(enc.encode(prompt + "".join(prompt_fragments)))) > TOKEN_LIMIT:
            logger.warning(
                "Reached token limit; stopping addition of further documents."
            )
            break  # Stop adding documents if token limit is exceeded

    full_prompt = prompt + "\n".join(prompt_fragments) + prompt_constraints

    return full_prompt


def nlp_topic_description(
    cluster: Cluster, api_key: str = settings.OPENAI_API_KEY
) -> str:
    """
    Generate a topic description based on topic keywords using ChatGPT.

    Parameters
    ----------
    cluster : Cluster
        A Cluster model instance.

    Returns
    -------
    str
        A description generated by ChatGPT based on the input keywords.

    Notes
    -----
    This function returns a dummy text if the application is in development
    mode (DEBUG) and there's no OPENAI_API_KEY configured in the settings.

    Examples
    --------
    >>> input_keywords = ["technology", "innovation", "future"]
    >>> description = nlp_topic_description(input_keywords)
    >>> logger.info(description)
    "This is a dev mode dummy summary text for topic keywords: technology,
    innovation, future"
    """
    if settings.DEBUG and not api_key:
        # returns dummy text if dev mode and there's no openai api key
        return (
            "This is a dev mode dummy summary text for topic keywords: "
            f"{cluster.topic}."
        )

    prompt = build_prompt(cluster)

    return call_chatgpt(prompt=prompt, api_key=api_key)
