from __future__ import annotations

import json
import logging

from typing import cast

import joblib
import numpy as np
import openai
import requests
import tiktoken

from django.conf import settings
from rago.augmented import AugmentedBase, OpenAIAug
from rago.extensions.cache import CacheFile
from rago.retrieval import StringRet

from literev.libs.chroma_utils import (
    chroma_client,
    # chroma_client_adm,
    chroma_client_penal,
    openai_client,
)
from literev.libs.rag_classes import HactarAug
from literev.libs.rag_pdf import prepare_chunks
from literev.models import (
    Cluster,
    ClusterElement,
    Document,
)

EMBEDDING_MODEL = "text-embedding-3-large"

logger = logging.getLogger(__name__)

CACHE_DIR = settings.LITEREV_CACHE_DIR / "rago"

MODULE_NAME = "hactar" if settings.USE_HACTAR_LLM else "openai"

AUG_CACHE = CacheFile(target_dir=CACHE_DIR / f"aug_nlp_{MODULE_NAME}")

USE_HACTAR_LLM = settings.USE_HACTAR_LLM
HACTAR_VERIFY_SSL = settings.HACTAR_VERIFY_SSL


def get_top_documents_from_cluster(
    cluster: Cluster, n: int = 10
) -> list[Document]:
    """
    Get the n most relevant documents from a cluster based on HDBSCAN probabilities.

    Parameters
    ----------
    cluster : Cluster
        The cluster to analyze
    n : int, optional
        Number of documents to return, by default 10

    Returns
    -------
    list[Document]
        List of the n most relevant Document objects
    """
    try:
        # Load saved HDBSCAN scores and document IDs
        hdbscan_scores = joblib.load(
            settings.ARTICLE_DATA
            / f"hdbscan_scores_project_{cluster.project.id}.pkl"
        )
        list_id_docs = joblib.load(
            settings.ARTICLE_DATA / f"id_list_project_{cluster.project.id}.pkl"
        )

        # Get documents in this cluster
        cluster_elements = ClusterElement.objects.filter(cluster=cluster)
        cluster_doc_ids = [elem.document.id for elem in cluster_elements]

        # Get indices of documents in this cluster
        cluster_indices = [
            list_id_docs.index(doc_id) for doc_id in cluster_doc_ids
        ]

        # Get probabilities for documents in this cluster
        cluster_probs = hdbscan_scores[cluster_indices]

        # Sort by probability and get top n
        top_indices = np.argsort(cluster_probs)[-n:][::-1]
        top_doc_ids = [cluster_doc_ids[i] for i in top_indices]

        # Get Document objects
        top_documents = Document.objects.filter(id__in=top_doc_ids)

        # Sort documents by their probability
        prob_dict = dict(zip(top_doc_ids, cluster_probs[top_indices]))
        sorted_documents = sorted(
            top_documents, key=lambda x: prob_dict[x.id], reverse=True
        )

        logger.info(
            f"Found {len(sorted_documents)} relevant documents for cluster {cluster.id}"
        )
        return sorted_documents

    except FileNotFoundError as e:
        logger.error(
            f"Could not load HDBSCAN data for project {cluster.project.id}"
        )
        logger.error(e)
        return list(
            Document.objects.filter(clusterelement__cluster=cluster)[:n]
        )


# Available models from hactar.unige.ch
MODEL_SPECS = {
    # Current model to consider across LiteRev
    "mistral-small3.1:24b": {
        "context_size": 128000,
        "encoding": "cl100k_base",
    },
    "qwen2.5:32b": {
        "context_size": 128000,
        "encoding": "cl100k_base",
    },
    "gemma3:27b": {
        "context_size": 128000,
        "encoding": "cl100k_base",
    },
    "yi:34b": {
        "context_size": 128000,
        "encoding": "cl100k_base",
    },
    "phi3:14b": {
        "context_size": 128000,
        "encoding": "cl100k_base",
    },
}

GPT_MODEL = "gpt-4.1-mini"
GPT_MODEL_MAX_TOKENS = 128000  # Check the limit It seems that for the model gpt 4.1 mini is around 1M
LLM_MODEL = "mistral-small3.1:24b"
MAX_TOKENS_RESPONSE = 250

# Get model specs with fallback values
current_model = MODEL_SPECS.get(
    LLM_MODEL, {"context_size": 128000, "encoding": "cl100k_base"}
)
LLM_MODEL_MAX_TOKENS = (
    cast(int, current_model["context_size"])
    if USE_HACTAR_LLM
    else GPT_MODEL_MAX_TOKENS
)
TOKEN_LIMIT = LLM_MODEL_MAX_TOKENS - MAX_TOKENS_RESPONSE - 400
RELEVANT_K = 10  # Number of relevant documents to consider when asking RAG


def call_model(prompt: str, api_key: str):
    """
    Call chosen LLM model via Open WebUI API endpoints.

    Sets the api_key, sends the prompt to hactar's servers,
    and returns the generated response.

    Parameters
    ----------
    prompt : str
        Input text prompt for LLM.

    api_key : str, optional
        The Open WebUI API key. Defaults to project settings.

    Returns
    -------
    str
        Response generated by LLM.

    References
    ----------
    More on Open WebUI: https://docs.openwebui.com/getting-started/api-endpoints

    Examples
    --------
    >>> response = call_model("What is the capital of France?")
    >>> logger.info(response)
    'The capital of France is Paris.'
    """

    url = "https://hactar.unige.ch/api/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    data = {
        "model": f"{LLM_MODEL}",
        "messages": [
            {
                "role": "user",
                "content": prompt,
                "max_tokens": MAX_TOKENS_RESPONSE,
                "temperature": 0.0,
            }
        ],
    }

    try:
        response = requests.post(
            url,
            headers=headers,
            json=data,
            verify=HACTAR_VERIFY_SSL,
        )
        response.raise_for_status()
        result = response.json()

        if "choices" in result and len(result["choices"]) > 0:
            return result["choices"][0]["message"]["content"]
        else:
            logger.error(f"Unexpected API response format: {result}")
            return ""

    except requests.exceptions.RequestException as e:
        logger.error(f"API request failed: {e}")
        return ""
    except json.JSONDecodeError as e:
        logger.error(f"Failed to decode API response: {e}")
        return ""


def call_chatgpt(prompt: str, api_key: str = settings.OPENAI_API_KEY) -> str:
    """
    Call ChatGPT via the OpenAI Python package.

    Sets the OpenAI API key, sends the prompt to ChatGPT,
    and returns the generated response.

    Parameters
    ----------
    prompt : str
        Input text prompt for ChatGPT.

    api_key : str, optional
        The OpenAI API key. Defaults to project settings.

    Returns
    -------
    str
        Response generated by ChatGPT.

    References
    ----------
    More on ChatGPT: https://platform.openai.com/docs/guides/chat/introduction

    Examples
    --------
    >>> response = call_chatgpt("What is the capital of France?")
    >>> logger.info(response)
    'The capital of France is Paris.'
    """

    messages = [{"role": "user", "content": prompt}]

    try:
        logger.info("Sending request to OpenAI ChatGPT API")
        response = openai_client.chat.completions.create(
            model=GPT_MODEL,
            messages=messages,  # type: ignore
            max_tokens=MAX_TOKENS_RESPONSE,
            temperature=0,
        )
    except openai.RateLimitError as e:
        if settings.DEBUG:
            logger.debug(f"RateLimitError in dev mode: {e}")
            return "RateLimit Error devmode dummy text"
        else:
            # if not in dev mode, log error and return empty string
            logger.error(f"OpenAI API RateLimitError: {e}")
            return ""
    except openai.OpenAIError as e:
        # all other OpenAI api errors will fall here and return an empty string
        logger.error(f"OpenAI API Error:{e}")
        return ""

    return cast(str, response.choices[0].message.content)


def build_prompt(cluster: Cluster, USE_HACTAR_LLM: bool) -> str:
    """
    Build a prompt for summarizing a cluster of law cases.

    Constructs a prompt to describe a cluster of law cases based on a predefined
    template. The function collects context from documents associated with the cluster
    and ensures the resulting prompt respects the model's token limit.

    Parameters
    ----------
    cluster : Cluster
        A Cluster object containing the topic and associated documents.

    Returns
    -------
    str
        A complete prompt formatted for LLM consumption.

    Notes
    -----
    - The function selects up to `RANDOM_K` words randomly from each document's preprocessed
      text for inclusion in the prompt.
    - If the token limit (`TOKEN_LIMIT`) is exceeded, additional documents are excluded.
    - Prompts are generated in French and include specific constraints to maintain
      response quality.

    Examples
    --------
    >>> cluster = Cluster.objects.get(id=1)
    >>> prompt = build_prompt(cluster)
    >>> print(prompt)
    """

    prompt_fragments: list[str] = []
    enc = tiktoken.get_encoding(
        cast(
            str, MODEL_SPECS.get(LLM_MODEL, {}).get("encoding", "cl100k_base")
        )
    )

    retrieval_prompt = (
        "You are a legal assistant specialized in generating queries for a RAG system."
        "Your role is to generate a single query in French that will be used to search"
        "a vector database containing legal documents from the canton of Geneva."
        "The following keywords represent the topic of a document cluster:\n{keywords}.\n"
        "Your task is to formulate a RAG query in French that maximizes the relevance of"
        "the search in this context. Your response must be only the"
        "query — no explanation, no commentary, nothing else."
    )

    prompt_template = """
        You are a Swiss lawyer specializing in the analysis of case law from the Geneva Court of Justice.
        Your task is to produce a concise, neutral, and factual summary in a single paragraph of a few sentences,
        based solely on the content of the provided text cluster keywords and additional context.
        Cluster keywords: {keywords}.

        Instructions:
        Do not make any assumptions or add any elements not present in the cluster.

        Identify only:
        the recurring central facts,
        the legal issues examined,
        the legal principles applied,
        the trends or solutions adopted.
        Do not cite any names, full dates, or superfluous details; maintain a sober and formal style.
        The summary should be no more than 4 to 6 sentences, in a single paragraph.

        If the cluster is heterogeneous, summarize the common theme or dominant issues.
        Expected output:
        A single paragraph accurately and concisely summarizing the content of the cluster.

        "In addition to the most important keywords, use "
        "the following additional context coming from the law cases contained in this cluster:"
        "\n"
        """

    prompt_constraints = "Write the response in French."

    cluster_documents = Document.objects.filter(
        clusterelement__cluster=cluster
    )

    doc_num = min(RELEVANT_K, len(cluster_documents))
    # Get the most relevant documents from the cluster
    documents = get_top_documents_from_cluster(cluster, n=doc_num)

    # Generate a better RAG query based on the cluster keywords
    if USE_HACTAR_LLM:
        rag_query = call_model(
            retrieval_prompt.format(keywords=cluster.topic),
            settings.HACTAR_API_KEY,
        )
    else:
        rag_query = call_chatgpt(
            retrieval_prompt.format(keywords=cluster.topic),
            settings.OPENAI_API_KEY,
        )

    logger.info(f"rag_query : {rag_query}")
    prompt = prompt_template.format(keywords=cluster.topic)

    for i, document in enumerate(documents, start=1):
        chunks = prepare_chunks(document.raw_document_text or "")

        retrieval = StringRet(chunks)

        if USE_HACTAR_LLM:
            augmented = cast(
                AugmentedBase,
                HactarAug(
                    api_key=settings.HACTAR_API_KEY,
                    top_k=5,
                    model_name="mxbai-embed-large:latest",  # model_name="nomic-embed-text", # suggested model to embed
                    cache=AUG_CACHE,
                ),
            )

        else:
            augmented = cast(
                AugmentedBase,
                OpenAIAug(
                    api_key=settings.OPENAI_API_KEY,
                    top_k=5,
                    model_name="text-embedding-ada-002",
                    cache=AUG_CACHE,
                ),
            )

        # Getting relevant chunks
        ret_data = retrieval.get(rag_query)
        document_context = augmented.search(rag_query, ret_data)

        # For now only get the chunk which got the best score
        document_context_str = document_context[-1].replace("\n", "")
        logger.info(f"document context : {document_context_str}")

        prompt_fragments.append(f"\ndocument {i} : " + document_context_str)

        if (len(enc.encode(prompt + "".join(prompt_fragments)))) > TOKEN_LIMIT:
            logger.warning(
                "Reached token limit; stopping addition of further documents."
            )
            break

    full_prompt = (
        prompt + "\n".join(prompt_fragments) + "\n" + prompt_constraints
    )
    logger.info(
        f"full prompt ({len(enc.encode(full_prompt))}) : {full_prompt}"
    )

    return full_prompt


PROMPT_CLUSTER_SUMMARY = """
        Les documents fournis sont des extraits ou résumés de décisions du Pouvoir judiciaire
        du canton de Genève (Suisse).

        Ta mission est de produire une synthèse factuelle et prudente du cluster de décisions,
        strictement limitée au contenu fourni.

        QUESTION / RECHERCHE (formulée en question, mots-clés ou requête booléenne) :
        {question}

        RÈGLES STRICTES (ANTI-HALLUCINATIONS) :
        Tu NE DOIS PAS inventer ou supposer des faits, dates, parties, lois, jurisprudences ou principes
        qui NE FIGURENT PAS explicitement dans les documents.
        Tu NE DOIS PAS déduire des normes du droit suisse ou genevois si le texte ne les mentionne pas.
        Tu NE DOIS PAS résumer en t'appuyant sur des connaissances externes ou générales :
        base-toi EXCLUSIVEMENT sur les documents fournis.
        Lie toujours tes affirmations à ce qui apparaît dans le cluster (même implicitement).
        Adopte un ton juridique neutre, prudent et descriptif.

        INSTRUCTIONS POUR LE RÉSUMÉ :
        Rédige un paragraphe court qui répond à la question à partir du contenu du cluster.
        Mets en lumière les motifs, principes ou tendances qui apparaissent dans les décisions.
        S'il y a divergence entre les décisions, mentionne-la.
        Reformule les informations sans citer textuellement sauf si essentiel.

        - Si la requête prend la forme d'une recherche par mots-clés ou booléenne (ex : "police and fils and cambriolage") :
            1. Indique clairement si, selon les documents fournis, la combinaison ou la co-occurrence recherchée des éléments est présente, partiellement présente, ou absente.
            2. Justifie brièvement la réponse en explicitant l'information pertinente trouvée (exemples, contexte).

        DOCUMENTS (DÉCISIONS DU POUVOIR JUDICIAIRE DE GENÈVE) :
        {context}

        RÉSUMÉ (STRICTEMENT BASÉ SUR LES DOCUMENTS) :
        """


def get_best_chunk_documents(collection, embedded_query, record_keys):
    """
    Return best ranked chunks sentences given embedded query.
    """
    documents = []
    for record_key in record_keys:
        results = collection.query(
            query_embeddings=embedded_query,
            where={
                "$and": [
                    {"record_key": record_key},
                    {"section": "Mineure-Subsommation"},
                ]
            },
            n_results=8,
            include=["documents"],
        )
        sentences = results.get("documents", [])
        documents.append(sentences[0] if sentences else [])

    return documents


def create_context(documents):
    """
    Create the context from documents senteces for prompt summary.
    """
    ctx = ""
    for idx, sents in enumerate(documents):
        sentences = "\n".join(sents)
        ctx += f"document {idx}:\n{sentences}\n"


def get_cluster_summary(
    cluster: Cluster,
    chamber_name: str,
    question: str,
    api_key: str = settings.HACTAR_API_KEY,
) -> str:
    """
    Return summary for a given cluster.
    """
    if settings.DEBUG and not api_key:
        # returns dummy text if dev mode and there's no openai api key
        return (
            "This is a dev mode dummy summary text for topic keywords: "
            f"{cluster.topic}."
        )
    top_docs = get_top_documents_from_cluster(cluster)

    record_keys = []
    for doc in top_docs:
        record_keys.append(doc.record_key)

    if chamber_name == "chambre_penale":
        collection = chroma_client_penal.get_collection(chamber_name)
    # elif chamber_name == "chambre_administrative":
    #     collection = chroma_client_adm.get_collection(chamber_name)
    else:
        collection = chroma_client.get_collection(chamber_name)

    embedded_query = (
        openai_client.embeddings.create(
            model=EMBEDDING_MODEL, input=[question]
        )
        .data[0]
        .embedding
    )
    documents = get_best_chunk_documents(
        collection, embedded_query, record_keys
    )

    ctx = create_context(documents)
    resp = openai_client.chat.completions.create(
        model=GPT_MODEL,
        messages=[
            {
                "role": "system",
                "content": "Tu es un modèle spécialisé dans l'analyse de jurisprudence suisse.",
            },
            {
                "role": "user",
                "content": PROMPT_CLUSTER_SUMMARY.format(
                    question=question, context=ctx
                ),
            },
        ],
        temperature=0,
    )
    answer = resp.choices[0].message.content
    return answer if answer else ""


def nlp_topic_description(
    cluster: Cluster, api_key: str = settings.HACTAR_API_KEY
) -> str:
    """
    Generate a topic description based on topic keywords using a LLM model.

    Parameters
    ----------
    cluster : Cluster
        A Cluster model instance.

    Returns
    -------
    str
        A description generated by an LLM based on the input keywords.

    Notes
    -----
    This function returns a dummy text if the application is in development
    mode (DEBUG) and there's no HACTAR_KEY configured in the settings.

    Examples
    --------
    >>> input_keywords = ["technology", "innovation", "future"]
    >>> description = nlp_topic_description(input_keywords)
    >>> logger.info(description)
    "This is a dev mode dummy summary text for topic keywords: technology,
    innovation, future"
    """
    if settings.DEBUG and not api_key:
        # returns dummy text if dev mode and there's no openai api key
        return (
            "This is a dev mode dummy summary text for topic keywords: "
            f"{cluster.topic}."
        )

    prompt = build_prompt(cluster, USE_HACTAR_LLM)

    if USE_HACTAR_LLM:
        return call_model(prompt=prompt, api_key=api_key)
    else:
        return call_chatgpt(prompt, api_key=settings.OPENAI_API_KEY)
