import logging

from typing import cast

import openai
import tiktoken

from django.conf import settings
from openai import OpenAI

from literev.models import Cluster, Document

# logger
logger = logging.getLogger(__name__)

# openai client
openai_client = OpenAI(api_key=settings.OPENAI_API_KEY)

# gpt model consumed by the api
GPT_MODEL = "gpt-3.5-turbo"

# max tokens accepted by gpt-3.5-turbo model
# openai plan on increasing the max tokens, more info at:
# https://openai.com/blog/new-models-and-developer-products-announced-at-devday
GPT_MODEL_MAX_TOKENS = 4096

# number of tokens reserved for gpt response
MAX_TOKENS_RESPONSE = 250

# 200 tokens extra margin for security
TOKEN_LIMIT = MAX_TOKENS_RESPONSE - MAX_TOKENS_RESPONSE - 200


def call_chatgpt(prompt: str, api_key: str = settings.OPENAI_API_KEY) -> str:
    """
    Call ChatGPT via the OpenAI Python package.

    Sets the OpenAI API key, sends the prompt to ChatGPT,
    and returns the generated response.

    Parameters
    ----------
    prompt : str
        Input text prompt for ChatGPT.

    api_key : str, optional
        The OpenAI API key. Defaults to project settings.

    Returns
    -------
    str
        Response generated by ChatGPT.

    References
    ----------
    More on ChatGPT: https://platform.openai.com/docs/guides/chat/introduction

    Examples
    --------
    >>> response = call_chatgpt("What is the capital of France?")
    >>> print(response)
    'The capital of France is Paris.'
    """

    messages = [{"role": "user", "content": prompt}]

    try:
        logger.info("Sending request to OpenAI ChatGPT API")
        response = openai_client.chat.completions.create(
            model=GPT_MODEL,
            messages=messages,  # type: ignore
            max_tokens=MAX_TOKENS_RESPONSE,
            temperature=0.4,  # this sets the creativity of the response
        )
    except openai.RateLimitError as e:
        if settings.DEBUG:
            logger.debug(f"RateLimitError in dev mode: {e}")
            return "RateLimit Error devmode dummy text"
        else:
            # if not in dev mode, log error and return empty string
            logger.error(f"OpenAI API RateLimitError: {e}")
            return ""
    except openai.OpenAIError as e:
        # all other OpenAI api errors will fall here and return an empty string
        logger.error(f"OpenAI API Error:{e}")
        return ""

    return cast(str, response.choices[0].message.content)


def build_prompt(cluster: Cluster) -> str:
    """
    Build ChatGPT prompt for a scientific topic description.

    Generates a prompt for ChatGPT to describe a scientific topic.
    The prompt follows a specific template, including topic keywords
    extracted from the cluster and relevant related articles for context.

    Parameters
    ----------
    cluster : Cluster
        A Cluster object which contains the topic field with the keywords
        and can also be used for querying related articles.

    Returns
    -------
    str
        Well-constructed ChatGPT prompt.

    Notes
    -----
    The generated prompt is based on a predefined template. It also includes
    constraints for response quality and templates for articles to provide
    context to ChatGPT.

    See Also
    --------
    prompt_template : str
        Base prompt template.
    prompt_constraints : str
        Constraints for response quality.
    article_prompt_template : str
        Template for each article.

    Examples
    --------
    >>> cluster = Cluster.objects.get(id=123)
    >>> prompt = build_prompt(cluster)
    """

    # base prompt used for generating the topic description
    prompt_template = (
        "Provide a concise and succinct general scientific topic description"
        "based on the following keywords: {keywords}, obtained from a term "
        "frequency inverse document frequency analysis. "
        "These keywords were selected based on a search of relevant articles. "
        "The following articles, from which these keywords were extracted via "
        "tf-idf, provide additional context:\n\n"
    )

    # constraints can be fine-tuned to prevent unwanted words or sentences
    # this is to prevent unwanted words or sentences
    prompt_constraints = (
        "Ensure the response maintains a narrative voice suitable for general "
        "scientific discussions while minimizing the use of pronouns. Focus "
        "on broader scientific concepts and applications. Avoid unnecessary "
        "introductions and redundancies. Avoid using quotes and backticks "
        "Avoid the use of the following keywords and expressions: keyword, "
        "keywords, This topic, This research, we propose, research, "
        "proposing, we, this report. Summarize it in two sentences."
    )

    # this template is used for each article
    article_prompt_template = (
        "Article {article_number}\n"
        "Title: {article_title}\n"
        "Abstract Sample: {article_abstract}.\n\n"
    )

    # inject topic keyword into prompt
    prompt = prompt_template.format(keywords=cluster.topic)

    # generate encoder based on specific gpt model
    enc = tiktoken.encoding_for_model(GPT_MODEL)

    # get all articles related to cluster(topic)
    articles = Document.objects.filter(clusterelement__cluster=cluster)

    # calculate initial number of tokens
    tokens_count = len(enc.encode(prompt)) + len(
        enc.encode(prompt_constraints)
    )

    # loop through all articles
    for article_number, article in enumerate(articles, start=1):
        # get article title
        article_title = article.title

        # get article abstract sentences by splitting it on "."
        abstract_sentences = article.abstract.split(".")

        article_abstract = (
            # get first 2 sentences if abstract is at least 2 sentences long
            ".".join(abstract_sentences[:2])
            if len(abstract_sentences) >= 2
            else article.abstract
        )

        # fill the article prompt template with current loop's article data
        article_prompt = article_prompt_template.format(
            article_number=article_number,
            article_title=article_title,
            article_abstract=article_abstract,
        )

        # count number of tokens in the article prompt
        article_tokens = len(enc.encode(article_prompt))

        # update tokens count for the next loop
        tokens_count = tokens_count + article_tokens

        # check if the token limit was reached
        if tokens_count > TOKEN_LIMIT:
            # break the loop without appending the article to the prompt
            break

        # limit not reached, append the article prompt to the 'main' prompt
        prompt = prompt + article_prompt

    # add constraints at the end of the prompt after the loop
    # gpt performs better if we pass the constraints at the end
    prompt = prompt + prompt_constraints
    return prompt


def nlp_topic_description(
    cluster: Cluster, api_key: str = settings.OPENAI_API_KEY
) -> str:
    """
    Generate a topic description based on topic keywords using ChatGPT.

    Parameters
    ----------
    cluster : Cluster
        A Cluster model instance.

    Returns
    -------
    str
        A description generated by ChatGPT based on the input keywords.

    Notes
    -----
    This function returns a dummy text if the application is in development
    mode (DEBUG) and there's no OPENAI_API_KEY configured in the settings.

    Examples
    --------
    >>> input_keywords = ["technology", "innovation", "future"]
    >>> description = nlp_topic_description(input_keywords)
    >>> print(description)
    "This is a dev mode dummy summary text for topic keywords: technology,
    innovation, future"
    """
    if settings.DEBUG and not api_key:
        # returns dummy text if dev mode and there's no openai api key
        return (
            "This is a dev mode dummy summary text for topic keywords: "
            f"{cluster.topic}."  # cluster.topic
        )

    prompt = build_prompt(cluster)

    return call_chatgpt(prompt=prompt, api_key=api_key)
