from __future__ import annotations

import datetime
import json

from itertools import chain
from typing import Any, Optional

from django.conf import settings
from django.db.models import Count

from literev.libs.select_functions import (
    get_filtered_document,
)
from literev.libs.update_project import (
    estimate_new_documents,
    get_actual_number_documents,
)
from literev.models import Cluster, Document, Project, ProjectRefinement
from literev.task_plotting import get_color_map
from literev.tasks import (
    get_shared_projects_ids,
)


def load_plot_data(project_pk: int) -> dict[str, str]:
    """
    Load and return the div and script plot data.

    This function reads the div and script plot data from the files
    generated by the clustering and plotting task. It returns a dictionary
    with two keys: "div_plot" and "script_plot". The values associated with
    these keys are the contents of the files.

    Parameters
    ----------
    project_pk : int
        The primary key of the project for which to load the plot data.

    Returns
    -------
    dict[str, str]
        A dictionary with two keys: "div_plot" and "script_plot".
        The values associated with these keys are the contents of the
        files generated by the clustering and plotting task.
    """
    fname_project_div_plot = settings.PLOT_DATA / f"{project_pk}_div.html"
    fname_project_script_plot = (
        settings.PLOT_DATA / f"{project_pk}_script.html"
    )

    with open(fname_project_div_plot, "r") as f:
        div_plot = f.read()

    with open(fname_project_script_plot, "r") as f:
        script_plot = f.read()

    return {"div_plot": div_plot, "script_plot": script_plot}


def extract_refined_list(
    project: Project, filter_field: str = "standards"
) -> list[str]:
    """
    Extract a refined list of unique and sorted values from a specified filter field in a project.

    This function retrieves values from the specified `filter_field` in documents
    associated with the given `project`, processes them to remove duplicates, and
    returns a sorted list of unique values.

    Parameters
    ----------
    project : Project
        The project from which to extract the refined list.
    filter_field : str, optional
        The field in the document model used to filter and extract values.
        Default is "standards".

    Returns
    -------
    list[str]
        A sorted list of unique values extracted and refined from the specified field.
    """
    filtered_list_raw = (
        Document.objects.filter(project=project)
        .order_by("result")
        .values_list(f"{filter_field}", flat=True)
    )

    flattened_values = chain.from_iterable(
        filter_value.split(";")
        for filter_value in filtered_list_raw
        if filter_value
    )

    refined_set = {value.strip() for value in flattened_values}

    return sorted(refined_set)


def get_grouped_clusters(project: Project) -> list[dict]:
    """
    Return grouped clusters with total documents.

    This function returns a list of dictionaries, each with a "topic" key
    and a "total_documents" key. The list is ordered by "total_documents"
    in descending order.

    Parameters
    ----------
    project : Project
        The project for which to retrieve grouped clusters.

    Returns
    -------
    list[dict]
        A list of dictionaries, each with a "topic" key and a
        "total_documents" key.
    """
    return (
        Cluster.objects.filter(project=project)
        .values("topic")
        .annotate(total_documents=Count("clusterelement__document"))
        .order_by("order")
    )


def format_grouped_clusters(grouped_clusters: list[dict]) -> list[str]:
    """
    Format the grouped clusters for display.

    This function takes the grouped clusters and formats them for display
    by creating a list of strings with the index and the first 10 topics
    separated by commas. The unclassified papers cluster is excluded.

    Parameters
    ----------
    grouped_clusters : list[dict]
        The grouped clusters with total documents.

    Returns
    -------
    list[str]
                The formatted list of strings.
    """
    UNCLASSIFIED_PAPERS_TOPIC = "unclassified papers"

    index = 0
    list_topic_10 = []
    exists_unclassified = False

    for cluster in grouped_clusters:
        if cluster["topic"] == UNCLASSIFIED_PAPERS_TOPIC:
            exists_unclassified = True
            continue
        index += 1
        number__topic10_cluster = (
            f"{index}: {', '.join(cluster['topic'].split(', ')[:10])}"
        )
        list_topic_10.append(number__topic10_cluster)

    if exists_unclassified:
        list_topic_10.append(UNCLASSIFIED_PAPERS_TOPIC)

    return list_topic_10


def validate_project_access(user, project_id: int) -> Optional[Project]:
    """
    Validate if the user has access to the specified project.

    Parameters
    ----------
    user : User
        The current user.
    project_id : int
        The ID of the project.

    Returns
    -------
    Optional[Project]
        The project object if access is valid, otherwise None.
    """
    shared_projects = get_shared_projects_ids()
    if (
        project_id in shared_projects
        or Project.objects.filter(user=user, id=project_id).exists()
    ):
        return Project.objects.filter(id=project_id).first()
    return None


def handle_filters_submission(
    user, project: Project, filters: dict[str, Any]
) -> dict[str, Any]:
    """
    Process a filters submission and generate a filtered document list.

    Parameters
    ----------
    user : User
        The current user.
    project : Project
        The project being processed.
    filters : dict[str, Any]
        Filters extracted from the request.

    Returns
    -------
    dict[str, Any]
        Context updates based on the filters submission.
    """
    refinement_limit = settings.LIMIT_NUMBER_REFINEMENTS
    current_refinement_count = ProjectRefinement.objects.filter(
        owner=user, project=project
    ).count()

    if current_refinement_count >= refinement_limit:
        return {"refinement_limit_exceeded": True}

    document_pk_list = get_filtered_document(project, filters)
    return {
        "filters": json.dumps(filters),
        "document_pk_list": " ".join(map(str, document_pk_list)),
        "number_document": len(document_pk_list),
        "AreYouSure": True,
    }


def prepare_update_context(project: Project) -> dict[str, Any]:
    """
    Prepare the context for confirming a project update.

    Parameters
    ----------
    project : Project
        The project being updated.

    Returns
    -------
    dict[str, Any]
        Context updates for rendering the update confirmation.
    """
    estimated_new_docs = estimate_new_documents(project)
    actual_docs = get_actual_number_documents(project)

    return {
        "confirm_update_project": True,
        "estimated_new_documents": estimated_new_docs,
        "new_total_documents": estimated_new_docs + actual_docs,
        "begin_date": project.range_begin_date,
        "new_end_date": datetime.date.today(),
        "new_project_name": f"{project.name} (updated)",
    }


def projectpage_load_final_results(user, project: Project) -> dict[str, Any]:
    """
    Load project data for rendering the project page.

    Parameters
    ----------
    user : User
        The current user.
    project : Project
        The project to load data for.

    Returns
    -------
    dict[str, Any]
        Context data for rendering the project page.
    """
    cluster_list = (
        Cluster.objects.filter(project=project)
        .values_list("topic", flat=True)
        .order_by("order")
    )
    grouped_clusters = get_grouped_clusters(project)
    refinements = ProjectRefinement.objects.filter(owner=user, project=project)

    context_data = {
        "project": project,
        "standard_list": extract_refined_list(project, "standards"),
        "descriptors_list": extract_refined_list(project, "descriptors"),
        "no_decision_list": extract_refined_list(project, "decision_type"),
        "result_list": [
            "REJETE",
            "ADMIS",
            "PARTIELMNT ADMIS",
            "IRRECEVABLE",
            "REFUSE",
            "ACCORDE",
            "RETIRE",
            "SANS OBJECT",
            "NO RESULT",
        ],
        "refinements": refinements,
    }

    if project.is_finish:
        topics, palette = get_color_map(list(cluster_list))
        plot_data = load_plot_data(project.pk)
        context_data.update(
            {
                "list_topics": list(cluster_list),
                "topic_colors": dict(zip(topics, palette)),
                "list_number_topic10": format_grouped_clusters(
                    grouped_clusters
                ),
                "div_plot": plot_data["div_plot"],
                "script_plot": plot_data["script_plot"],
            }
        )

    return context_data
