name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HOST_UID: 1001
  HOST_GID: 1001
  DOCKER_CPU_LIMIT: 1.0
  DOCKER_CPU_RESERVATION: 0.5
  LITEREV_USE_MULTIPROCESSING: false
  NUMBER_ARTICLE_BY_PAGE: 30
  NUMBER_THREADS_ALLOWED: 4
  NUMBER_TRIALS: 2
  NUMBER_OPTUNA_JOBS: 5
  ENV: dev
  DEBUG: True
  DJANGO_SETTINGS_MODULE: config.settings.dev
  DJANGO_SECRET_KEY: "django-insecure-96*q09uh20(^i4sdxqh3n_v#d-o:**7zrri&k-j3@f10hm88)"
  DJANGO_ENV: dev
  ES_HOST_URL: "http://95.216.201.202:9200"
  ES_PASSWORD: "I39hAE_bvikcbRHNhyvf"
  ES_USERNAME: "elastic"
  MEDIA_ROOT: /opt/data/literev/static/media
  FRONTEND_HOST_PORT: 8000
  POSTGRES_PORT: 35432
  POSTGRES_HOST: localhost  # literev-postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB_LITEREV: literev
  POSTGRES_USER_LITEREV: literev
  POSTGRES_PASSWORD_LITEREV: literevqsx3409po
  POSTGRES_DATA: /opt/data/literev/postgres
  POSTGRES_HOST_BACKUP: /opt/data/literev/backup
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CERTBOT_EMAIL: ci@literev.unige.ch
  CERTBOT_DOMAIN: literev.unige.ch
  STATIC_ROOT: /opt/data/literev/static
  LITEREV_CACHE_DIR: /opt/data/literev/cache
  ACTIONS_RUNNER_DEBUG: true
  PUBMED_REQUEST_TIME_INTERVAL: 0.5
  PUBMEDCENTRAL_REQUEST_TIME_INTERVAL: 0.5
  CONTAINER_VOLUME_DATA_DIR: /opt/data/literev
  USE_CONTAINER: False
  SUGAR_ENV: test
  REDIS_PORT: 6379
  REDIS_HOST: localhost
  REDIS_DB: 0

jobs:
  check_branch:
    name: Check if branch is ahead of main
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Check if branch is ahead of main
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if ! git merge-base --is-ancestor origin/main ${{ github.event.pull_request.head.sha }};
          then echo "This branch is not up to date with main";
          exit 1; fi

  test:
    runs-on: self-hosted
    timeout-minutes: 30
    strategy:
      matrix:
        python_version: ["3.10"]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Install Operating System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gettext-base

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        environment-file: conda/base.yaml
        channels: conda-forge,nodefaults
        activate-environment: literev-legal
        auto-update-conda: true
        conda-solver: libmamba

    - name: Create environment variables files
      run: |
        export FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}
        export POSTGRES_PORT=${POSTGRES_PORT}
        export DOCKER_PROJECT_NAME=$RANDOM
        export HOST_UID=${HOST_UID}
        export HOST_GID=${HOST_GID}
        envsubst < .env.tpl > .env

    - name: Check if poetry.lock is updated
      run: poetry check

    - name: Install dependencies
      run: poetry install

    - name: Create volumes
      run: |
        mkdir -p ${CONTAINER_VOLUME_DATA_DIR}
        mkdir -p ${POSTGRES_HOST_BACKUP}

    - name: Clean-up and Setup
      run: |
        makim clean.all
        makim containers.host-setup

    - name: Remove old database
      run: sugar compose down --options --volumes || true

    - name: Build images
      run: sugar compose build --services literev-postgres

    - name: Start literev-postgres container
      run: sugar compose-ext start --options -d

    - name: Migrate containers
      run: makim django.migrate

    - name: Check migration files
      if: ${{ success() || failure() }}
      run: makim --verbose django.makemigrations --check

    - name: Run tests
      if: ${{ success() || failure() }}
      run: makim tests.unit --clean-cov

    - name: Set coverage report
      id: parse-coverage-report
      run: |
          COVERAGE_REPORT=$(makim tests.coverage-report)
          COVERAGE_PERCENTAGE=$(echo $COVERAGE_REPORT | grep -oP "TOTAL.* \K(\d{1,3})%")
          COVERAGE_PERCENTAGE=${COVERAGE_PERCENTAGE%?}
          STATE=$(if ((COVERAGE_PERCENTAGE<50)); then echo "critical"; elif ((50<=COVERAGE_PERCENTAGE && COVERAGE_PERCENTAGE<=74)); then echo "yellow"; elif ((75<=COVERAGE_PERCENTAGE)); then echo "success"; fi)
          COVERAGE_REPORT="${COVERAGE_REPORT//'%'/'%25'}"
          COVERAGE_REPORT="${COVERAGE_REPORT//$'\n'/'%0A'}"
          COVERAGE_REPORT="${COVERAGE_REPORT//$'\r'/'%0D'}"
          DABGE="https://img.shields.io/static/v1?label=Code%20Coverage&message=${COVERAGE_PERCENTAGE}%&color=${STATE}"
          echo "::set-output name=COVERAGE_REPORT::$COVERAGE_REPORT"
          echo "::set-output name=DABGE::$DABGE"

    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          ![Code Coverage](${{ steps.parse-coverage-report.outputs.DABGE }})
          ```
          ${{ steps.parse-coverage-report.outputs.COVERAGE_REPORT }}
          ```
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'

    - name: Stop services
      run: |
        sugar compose stop
        sugar compose down --options --volumes

    - name: Semantic Release PR Title Check
      uses: osl-incubator/semantic-release-pr-title-check@v1.4.1
      if: ${{ success() || failure() }}
      with:
        convention-name: conventionalcommits

  linter:
    runs-on: self-hosted
    timeout-minutes: 10
    strategy:
      matrix:
        python_version: ["3.10"]
    concurrency:
      group: ci-linter-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Install Operating System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gettext-base

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        environment-file: conda/base.yaml
        channels: conda-forge,nodefaults
        activate-environment: literev-legal
        auto-update-conda: true
        conda-solver: libmamba

    - name: Create environment variables files
      run: |
        export FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}
        export POSTGRES_PORT=${POSTGRES_PORT}
        export DOCKER_PROJECT_NAME=$RANDOM
        export HOST_UID=${HOST_UID}
        export HOST_GID=${HOST_GID}
        export USE_CONTAINER=True
        cd /home/runner/work/literev-legal/literev-legal/
        envsubst < .env.tpl > .env

    - name: Install dependencies
      run: poetry install

    - name: Run linter
      run: makim tests.lint

  containers:
    runs-on: self-hosted
    timeout-minutes: 30
    strategy:
      matrix:
        python_version: ["3.10"]
    concurrency:
      group: ci-containers-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    env:
      USE_CONTAINER: True
      SUGAR_ENV: dev

    steps:
    - uses: actions/checkout@v4

    - name: Install Operating System dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gettext-base

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        environment-file: conda/base.yaml
        channels: conda-forge,nodefaults
        activate-environment: literev-legal
        auto-update-conda: true
        conda-solver: libmamba

    - name: Create environment variables files
      run: |
        export FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}
        export POSTGRES_PORT=${POSTGRES_PORT}
        export DOCKER_PROJECT_NAME=$RANDOM
        export HOST_UID=${HOST_UID}
        export HOST_GID=${HOST_GID}
        cd /home/runner/work/literev-legal/literev-legal/
        envsubst < .env.tpl > .env

    - name: Install dependencies
      run: poetry install

    - name: Create volumes
      run: |
        mkdir -p ${CONTAINER_VOLUME_DATA_DIR}
        mkdir -p ${POSTGRES_HOST_BACKUP}

    - name: Clean-up and Setup
      run: |
        makim clean.all
        makim containers.host-setup

    - name: Remove old database
      run: sugar compose down --options --volumes || true

    - name: Build images
      run: sugar compose build

    - name: Start containers
      run: sugar compose-ext restart --options -d

    - name: Containers' info
      run: |
        sleep 30
        sugar compose ps

    - name: Stop services
      run: |
        sugar compose stop
        sugar compose down --options "--volumes"
