name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LITEREV_USE_MULTIPROCESSING: false
  NUMBER_ARTICLE_BY_PAGE: 30
  NUMBER_THREADS_ALLOWED: 4
  NUMBER_TRIALS: 2
  ENV: dev
  DEBUG: True
  DJANGO_SECRET_KEY: "django-insecure-96*q09uh20(^i4sdxqh3n_v#d-o:**7zrri&k-j3@f10hm88)"
  DJANGO_ENV: dev
  DJANGO_SETTINGS_MODULE: config.settings
  DJANGO_MEDIA_ROOT: /tmp/literev/media
  FRONTEND_HOST_ADDRESS: literev
  POSTGRES_HOST: localhost  # literev-postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB_LITEREV: literev
  POSTGRES_USER_LITEREV: literev
  POSTGRES_PASSWORD_LITEREV: literevqsx3409po
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CERTBOT_EMAIL: ci@literev.unige.ch
  CERTBOT_DOMAIN: literev.unige.ch
  STATIC_ROOT: /tmp/literev/static
  LITEREV_CACHE_DIR: /tmp/literev/cache
  ACTIONS_RUNNER_DEBUG: true
  PUBMED_REQUEST_TIME_INTERVAL: 0.5
  PUBMEDCENTRAL_REQUEST_TIME_INTERVAL: 0.5
  DOCKER_VOLUME_CONTAINER_PATH: /tmp/literev/storage

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python_version: ["3.10"]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/environment.yaml
        channels: conda-forge,nodefaults
        activate-environment: literev-legal
        use-mamba: true
        miniforge-variant: Mambaforge
          
    - name: Create environment variables files
      run: |
        export FRONTEND_HOST_PORT=$RANDOM
        export POSTGRES_PORT=$RANDOM
        export DOCKER_PROJECT_NAME=$RANDOM
        export HOST_UID=$(id -u)
        export HOST_GID=$(id -g)
        envsubst < .env.tpl > .env

    - name: Create folder in the host side
      run: |
        mkdir -p ${DJANGO_MEDIA_ROOT}

    - name: Check if poetry.lock is updated
      run: poetry check

    - name: Install dependencies
      run: poetry install

    - name: Clean-up
      run: makim clean.all

    - name: Remove old database
      run: sugar down --options --volumes || true

    - name: Build images
      run: sugar build --services literev-postgres

    - name: Start literev-postgres container
      run: sugar ext start --services literev-postgres,literev --options -d

    - name: Migrate containers
      run: makim django.migrate

    - name: Health check
      run: |
        sleep 10
        docker ps
        # makim containers.wait-all

    - name: Check migration files
      if: ${{ success() || failure() }}
      run: makim --verbose django.makemigrations --check

    - name: Stop services
      run: |
        sugar stop
        sugar down --options --volumes
